### ISSUE TITLE
Validate MathML input

### ISSUE THREAD

**Issue by tamuri** [ModellingWebLab/cellmlmanip#10]
Note from Jonathan:
> This would be a separate module, probably just validating against a (RELAX NG) schema. There's one in the old pycml.

**Comment by MichaelClerx** [comment]
Note: Not sure libCellML is planning to take care of this

**Comment by nickerso** [comment]
libCellML validation currently validates MathML strings against the MathML 2.0 DTD and I think also checks that `<ci>`'s only make use of variables defined in the component.

**Comment by MichaelClerx** [comment]
Thanks!
