### ISSUE TITLE
Cellmlmanip breaks when using newer networkx

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#102]
Currently pinned to 2.3, breaks if using 2.4

**Comment by skeating** [comment]
Yes I hit this using weblab-fc. Do we want to fix it by insisting that we have 2.3 or fix for 2.4

**Comment by MichaelClerx** [comment]
Someone will have to fix it so that it works for both

**Comment by MichaelClerx** [comment]
Or possibly only 2.4 :D

**Comment by MichaelClerx** [comment]
https://networkx.github.io/documentation/stable/release/release_2.4.html

Think .node was deprecated since 2.1, if I'm reading this correctly. So could perhaps require 2.1 or greater and apply this fix?

**Comment by MichaelClerx** [comment]
```G.node –> use G.nodes```
