### ISSUE TITLE
Set up CI using Travis

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/cellmlmanip#11]
Including testing on multiple Python versions; at least 2.7 and 3.6.

**Comment by jonc125** [comment]
Should we close this, or leave open for Python 2.7 support?

**Comment by tamuri** [comment]
As this work is primarily for internal use, are we willing to make Python 3 a hard requirement? I'd be happy if it were so, and therefore close this issue.

**Comment by jonc125** [comment]
I'm fine to do that. We can revisit Python2 at a later date if required by users.
