### ISSUE TITLE
Issues arising from testing models in non standard units in weblab-fc 

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#110]
Issues that arise resulting from addressing https://github.com/ModellingWebLab/weblab-fc/issues/22 

[ ] A model that uses seconds does not have milliseconds in the registry and so unit conversion fails.
e.g.  earm_noble_model_1990

**Comment by jonc125** [comment]
Yeah, you need to add the units you want (from the protocol) to the registry always just in case.

**Comment by skeating** [comment]
> Yeah, you need to add the units you want (from the protocol) to the registry always just in case.
So how to tackle this one:
1. When cellmlmanip reads in a model, it always adds ms, mV, mM if not present just in case
2.  When weblab-fc reads the protocol it adds any missing units to the model

My first thought was 1 as its a belt and braces fix BUT if there are likely to be other units it needs to be 2 and this issue needs to be in weblab-fc.

Thoughts ?

**Comment by jonc125** [comment]
It should be (2). We don't want any 'magically defined' units beyond the CellML built-in stuff as this could lead to surprising failures. Chaste code generation adds the units it needs to the registry. Each protocol adds the units it defines - in its units definition section - similarly. A protocol should not reference any units apart from those it defines or built-in units (and weblab-fc ought to check for this and complain if not).

**Comment by skeating** [comment]
This is a weblab-fc issue - so closing here
