### ISSUE TITLE
Numbers in model get created as dimensionless symbols regardless of units given

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#111]
Reading in

'<cn cellml:units="millivolt">115</cn>'

results in a number symbol that has units dimensionless.

This causes issues for unit conversion that may need to happen to run a certain protocol.

**Comment by jonc125** [comment]
What's the context for this? I thought cellmlmanip did parse the `cellml:units` attribute on `cn` elements?

**Comment by skeating** [comment]
The context was that whilst trying to sort models with conversions in weblab-fc I hit a situation where I got an exception from the read in cellmlmanip. It was adding a variable to a number and claimed the number was dimensionless and so units of the 'add' caused a fail.

Currently failing to reproduce this in cellmlmanip; as it looks like you are correct.

**Comment by skeating** [comment]
Closing as I confused this #90
