### ISSUE TITLE
Add comments or docstrings to tests

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#113]
The tests are largely undocumented. This is a big issue, as the tests will be the main point where people start debugging. It should be possible to know what the code is trying to do, without having to infer this from the code itself (e.g. what if the code is wrong)

At the very least it should be explained what a test is testing, E.g. `TestHodgkin` doesn't tell you which part of cellmlmanip is tested.

**Comment by skeating** [comment]
In doing my update to testing I added docstrings to all functions EXCEPT those in transpiler.py - since these are pretty obvious.
