### ISSUE TITLE
Ensure tests have sensible names

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#114]
If someone wants to find a test for a specific bit of the code, it should be easy to find where that is.
So ideally we'd have test names that are something like TestX with all tests for class X in it. For bigger classes maybe we can have partial ones, like TestXxYy for method Yy in class Xx, or Yy could indicate a group of methods e.g. unit handling ones

**Comment by jonc125** [comment]
See also #91.
