### ISSUE TITLE
Issue with pycml derived RDF metadata tags

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/cellmlmanip#115]
I only just realised when testing the `bondarenko_model_2004_apex` model but I need to be able to pull out pycml rdf metadata. sadly the existing methods don't seem to work, unless I'm missing something?
In particular see https://chaste.cs.ox.ac.uk/trac/wiki/ChasteGuides/CodeGenerationFromCellML
I need to be able to pull out the `named-attribute` (`name`, `value`)
and also for `modifiable-parameter`  (yes/no), `derived-quantity ` (yes/no), `is-self-excitatory ` (yes/no), `range-low` and `range-low`  pairs.

I have a sort-of workaround but I can't figure out how to guarantee the variables appear **in document order**. This is important!

```
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
   <rdf:Description rdf:about="#luo_rudy_1991">
      <named-attribute xmlns="https://chaste.comlab.ox.ac.uk/cellml/ns/pycml#">
         <rdf:Description>
            <name rdf:datatype="http://www.w3.org/2000/10/XMLSchema#string">SuggestedCycleLength</name>
            <value rdf:datatype="http://www.w3.org/2000/10/XMLSchema#double">750</value>
         </rdf:Description>
      </named-attribute>
      <named-attribute xmlns="https://chaste.comlab.ox.ac.uk/cellml/ns/pycml#">
         <rdf:Description>
            <name rdf:datatype="http://www.w3.org/2000/10/XMLSchema#string">SuggestedForwardEulerTimestep</name>
            <value rdf:datatype="http://www.w3.org/2000/10/XMLSchema#double">0.005</value>
         </rdf:Description>
      </named-attribute>
   </rdf:Description>
</rdf:RDF>```

**Comment by jonc125** [comment]
I'm guessing you use `Model._get_symbols_by_rdf` (which should become a public method) to get relevant symbols? And then you just need to sort that list by order added? So I'd recommend:
1. Make the method public
2. Add a new public method `sort_symbols` which does `return sorted(symbols, key=lambda var: self.get_meta_dummy(var.args[0]).order_added)` and use it to sort your variables whenever needed
3. Make `get_derivative_symbols` and `get_state_symbols` use `sort_symbols`

I'm not sure whether `_get_symbols_by_rdf` should always return a sorted list, or whether it should return a set and the user has the option to sort later. At present the length of the return value will always be pretty short so probably doesn't much matter. Looks like pycml returns unsorted lists and lets the user sort if desired.

**Comment by jonc125** [comment]
Look at `output_model_attributes` in `pycml/translators.py`: some of those properties annotate the model, not variables. Look at `output_verify_state_variables` for how the `range-` properties are used.

Also, for some of these variable lists (e.g. modifiable parameters, derived quantities) pycml sorts by display name, not document order:
```
        # Find annotated parameters
        self.cell_parameters = filter(
            lambda v: v.is_modifiable_parameter,
            cellml_metadata.find_variables(self.model,
                                           ('pycml:modifiable-parameter', NSS['pycml']),
                                           'yes'))

        # Reduce intra-run variation
        self.cell_parameters.sort(key=self.var_display_name)
```
and
```
        # Find & store derived quantities, for use elsewhere
        self.derived_quantities = cellml_metadata.find_variables(self.model,
                                                                 ('pycml:derived-quantity', NSS['pycml']),
                                                                 'yes')
        # Reduce intra-run variation
        self.derived_quantities.sort(key=self.var_display_name)
```

**Comment by skeating** [comment]
@MauriceHendrix can you say what the conclusion was about what is needed here ?

**Comment by MauriceHendrix** [comment]
> @MauriceHendrix can you say what the conclusion was about what is needed here ?

I'll be working on it today might need a slightly adapted `_get_symbols_by_rdf` or a new method. I'll look at at and propose something in a pull request later today

**Comment by MauriceHendrix** [comment]
>         # Reduce intra-run variation
>         self.derived_quantities.sort(key=self.var_display_name)

Aha! so that's basically sorted by name!

**Comment by jonc125** [comment]
> Aha! so that's basically sorted by name!

Basically yes, although it's not identical to the name as given in the CellML file - iirc annotated variables use the ontology name instead. You can see the details in the definition of the `var_display_name` function.
