### ISSUE TITLE
Possible bug with identifying free variable

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#121]
I was using a very basic file to test model functions I hit the apparently unreachable code which says I have no free variable in the model (line 520 model.py)

Stepping through the code that looks for the free variable loops through the nodes of the graph. However, when creating the graph, a variable (state/free) of a derivative is only added as a node if it occurs on the rhs of the derivative; which since model uses dsv11/dt = 1 't' does not appear on rhs. So the Model object marks it as a free variable BUT no graph node ever gets created so it cannot be looked up.

Is this a bug ?

**Comment by skeating** [comment]
<?xml version='1.0'?>
<model cmeta:id="test_basic_ode" name="test_basic_ode" xmlns="http://www.cellml.org/cellml/1.0#" xmlns:cellml="http://www.cellml.org/cellml/1.0#" xmlns:cmeta="http://www.cellml.org/metadata/1.0#">
    <units name="ms">
        <unit prefix="milli" units="second"/>
    </units>
    <units name="per_ms">
        <unit exponent="-1" units="ms"/>
    </units>
    <units name="mV">
        <unit prefix="milli" units="volt"/>
    </units>
    <units name="per_mV">
        <unit exponent="-1" prefix="milli" units="volt"/>
    </units>
    <units name="mV_per_ms">
        <unit exponent="1" units="mV"/>
        <unit exponent="-1" units="ms"/>
    </units>
    <component name="environment">
        <variable cmeta:id="time" name="time" public_interface="out" units="ms"/>
    </component>
    <component name="env_ode">
        
        <variable name="time" public_interface="in" units="ms"/>
        <variable cmeta:id="sv11" initial_value="2" name="sv1" units="mV"/>
        <math xmlns="http://www.w3.org/1998/Math/MathML">
            <apply>
                <eq/>
                <apply>
                    <diff/>
                    <bvar>
                        <ci>time</ci>
                    </bvar>
                    <ci>sv1</ci>
                </apply>
                <cn cellml:units="mV_per_ms">1</cn>
            </apply>
        </math>
    </component>
    <group>
        <relationship_ref relationship="encapsulation"/>
        <component_ref component="environment"/>
        <component_ref component="env_ode"/>
    </group>
    <connection>
        <map_components component_1="env_ode" component_2="environment"/>
        <map_variables variable_1="time" variable_2="time"/>
    </connection>
    <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
        <rdf:Description xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf:about="#time">
            <bqbiol:is xmlns:bqbiol="http://biomodels.net/biology-qualifiers/" rdf:resource="https://chaste.comlab.ox.ac.uk/cellml/ns/oxford-metadata#time" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
        </rdf:Description>
    </rdf:RDF>
    <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
        <rdf:Description xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf:about="#sv11">
            <bqbiol:is xmlns:bqbiol="http://biomodels.net/biology-qualifiers/" rdf:resource="https://chaste.comlab.ox.ac.uk/cellml/ns/oxford-metadata#sodium_reversal_potential" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>
        </rdf:Description>
    </rdf:RDF>
</model>

**Comment by skeating** [comment]
Model here https://github.com/ModellingWebLab/cellmlmanip/blob/making-tests-clearer/tests/cellml_files/basic_ode.cellml

**Comment by jonc125** [comment]
Yeah, that's a bug! Not sure off the top of my head the most appropriate fix. Sounds like we do have a variable object with the correct type, so maybe just the error check needs to change?

**Comment by MauriceHendrix** [comment]
Definitely a bug and one I need fixing soon-ish if possible.

I get  No free variable set in model. for `demir_model_1994` and other models without `membrane_stimulus_current` oxmeta and `is-self-excitatory` metadta

**Comment by skeating** [comment]
So with a model that has ds/dt = 1/t I get a graph with two nodes:
ds/dt which has an 'equation' value
t which has a 'variableType' value of free (as well as name/value/units)
there is one edge between them

In a model ds/dt = 1 I get a graph with one node 
ds/dt which has an 'equation' value

So do I
1. adjust the graph so that in second case I would add my free variable node
  - if so, do I give it an edge to the derivative
2. adjust the get free symbol function to look at variables in graph if there is no node marked as free symbol.

At present my plan is to code both and see if I get any errors anywhere else in cellmlmanip; but I think issues are more like to arise elsewhere. I could always code each as separate branch so cg/fc can test and see if either causes issues.

Thoughts ??


and no edges

**Comment by jonc125** [comment]
I think the graph should have a node for `t`, but not an edge from the equation to that variable, since the dependency from an ODE to its free variable is different from if the free variable occurs on the RHS. In the latter case you need the variable defined in order to evaluate the equation; in the former case you don't actually care what the current time is.

**Comment by skeating** [comment]
okay added as a node but no edge
