### ISSUE TITLE
precision issue with get_conversion_factor giving 0.9999999999999999 instead of 1.0

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/cellmlmanip#122]
I get:
the following:
`model.units.get_conversion_factor(concentration_units, millimolar)` gives `1.0`
but
`model.units.get_conversion_factor(millimolar,concentration_units)` gives `0.9999999999999999`

This is a precision error also should this really give 1.0 or give an error?

```<units name="concentration_units">
   <unit units="mole" prefix="nano"/>
   <unit units="metre" prefix="milli" exponent="-3"/>
</units>```

'millimolar': [{'units': 'mole', 'prefix': 'milli'}, {'units': 'litre', 'exponent': '-1'}]

**Comment by jonc125** [comment]
Those numbers are equal to within double-precision floating point tolerances I think?

**Comment by MauriceHendrix** [comment]
> Those numbers are equal to within double-precision floating point tolerances I think?

exactly so I would expect `get_conversion_factor` to recognize that and give me 1.0.

Surely cellmlmanip needs a convenient way to recognize that 2 units are the same without having to mess with float point tolerances?

**Comment by mirams** [comment]
Yeah, I'd agree that we first want a Boolean check that units are the same that can return exactly one or true, so that preferably no scaling factor is added, or that scaling factor is exactly one.

**Comment by jonc125** [comment]
Hmm.
```
>>> 0.9999999999999999 == 1.0
False
>>> 0.99999999999999999 == 1.0
True
>>> 0.99999999999999995 == 1.0
True
>>> 0.99999999999999994 == 1.0
False
```
So it's not coming out as exactly 1!

**Comment by MauriceHendrix** [comment]
> Yeah, I'd agree that we first want a Boolean check that units are the same that can return exactly one or true, so that preferably no scaling factor is added, or that scaling factor is exactly one.

That's what I'm doing at the moment but that's on the assumption that asking for a factor between the same units will give 1.0

> Hmm.
> 
> ```
> >>> 0.9999999999999999 == 1.0
> False
> >>> 0.99999999999999999 == 1.0
> True
> >>> 0.99999999999999995 == 1.0
> True
> >>> 0.99999999999999994 == 1.0
> False
> ```
> 
> So it's not coming out as exactly 1!

```>>> abs(0.9999999999999999 -1.0) <= sys.float_info.epsilon
True
>>> abs(0.99999999999999999 -1.0) <= sys.float_info.epsilon
True
>>> abs( 0.99999999999999995 -1.0) <= sys.float_info.epsilon
True
>>> abs( 0.9999999999999999 -1.0) <= sys.float_info.epsilon
True
>>> abs( 0.0 -1.0) <= sys.float_info.epsilon
False
>>>```

**Comment by jonc125** [comment]
pycml claims two units are equal if their multiplicative factors are within a relative tolerance of 10^-6. We could do the same in cellmlmanip?

Or we could just make `get_conversion_factor` return 1 if the result is within epsilon of 1, given Maurice's check above?

**Comment by mirams** [comment]
There's no units in Sympy or equivalent thing that can say whether two units are symbolically equivalent? It's a bit untidy doing rounding on things that don't need it in principle.

**Comment by MauriceHendrix** [comment]
Normally you'd just get 1.0 in this example we are comparing:

**nanomole * millimeter^-3** to **millimole * litre-1**

**Comment by MichaelClerx** [comment]
Think you can't really avoid this when playing with conversion factors. Ran into it in Myokit as well and eventually had to solve with better float checking:

https://github.com/MichaelClerx/myokit/blob/master/myokit/_expressions.py#L2610

https://github.com/MichaelClerx/myokit/blob/master/myokit/_aux.py#L1338-L1359

**Comment by mirams** [comment]
Maybe to be completely general for multiplications by universal constants and things, but most of the units conversions we are interested in are integer operations on the powers of ten. There must be some way to recognise these and do them cleanly when they come out as 1?

**Comment by MauriceHendrix** [comment]
of course there is but then we'd be implementing our own unit conversion, wasn't the point of using pints that it made this easy? Anyway if we know that we're mostly working with factors of 10, can we just use math.isclose(factor, 1.0) and just return 1.0?

**Comment by MichaelClerx** [comment]
#141
