### ISSUE TITLE
What happens if models are not in "assignment form"? (DAEs)

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#124]
In CellML models, equations can be anything. But in practice they're almost always in "assignment form", where each variable `x` has an equation `x = ...` or `dx/dt = ...`.

Just looking at the equation graph code:

https://github.com/ModellingWebLab/cellmlmanip/blob/be2886839b21a8c4a6cb4c17efb84eeb4f60da6c/cellmlmanip/model.py#L359-L362

which calls

https://github.com/ModellingWebLab/cellmlmanip/blob/be2886839b21a8c4a6cb4c17efb84eeb4f60da6c/cellmlmanip/model.py#L681-L694

So this second method can deal with more complex LHS expressions, e.g. `1 + x = ...`, but will then return `x` as the only symbol, and then the method will continue as normal. (It only complains if it finds more than one symbol). It then stores the `eq`, so this _might_ be ok and slightly more flexible than only allowing assignment form (although we still wouldn't allow `1 = x` or `a + b = 10; a * b = 16`)

Is this by design? Otherwise, if we're only expecting assignment form we should make the `get_symbols_for` method less clever and raise errors if we encounter a DAE?

Thoughts @tamuri & @jonc125 ?

**Comment by MichaelClerx** [comment]
I think having `1 + x = ...` would go wrong here anyway:

https://github.com/ModellingWebLab/cellmlmanip/blob/be2886839b21a8c4a6cb4c17efb84eeb4f60da6c/cellmlmanip/model.py#L442-L456

**Comment by tamuri** [comment]
I never considered anything but a single symbol or derivative on the lhs so it would have to be reworked if that's not the case. If it passes that assertion (e.g. `1+x`) I think they'll be undefined behaviour later on!

**Comment by jonc125** [comment]
Yeah, at the moment we're definitely assuming assignment form (as pycml does). Quite a few things would need careful consideration if this changed!

**Comment by MichaelClerx** [comment]
OK, have added a check & test to #123. Maybe I can repurpose that PR for this issue?
