### ISSUE TITLE
Rename `Model.find_variable` ?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#125]
https://github.com/ModellingWebLab/cellmlmanip/blob/be2886839b21a8c4a6cb4c17efb84eeb4f60da6c/cellmlmanip/model.py#L696-L711

Returns a list of matches, which are dummies for either numbers or variables.

Maybe rename to `get_symbols_by_metadata` and add a check to ignore numbers?

Could also be private as only used when creating equation graph at the moment

**Comment by jonc125** [comment]
Obsoleted by #136.
