### ISSUE TITLE
Shall we make Model.graph a @property?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#128]
At the moment we're directly accessing .graph any time we want it, and assuming the user has already called the method to create the graph.

How about we rewrite it like this:

```
class Model(object):
  def __init__(self):
    self._graph = None
  @property
  def graph(self):
    if self._graph is not None:
      return self._graph
    # Code from get_equation_graph goes here, minus the refresh option
```

Then to refresh you would have to do
```
self._graph = None
```
I think this is fine because invalidating the cached graph should be the Model's responsibility, not something an external class does / knows how to do.

Thoughts @jonc125 @tamuri ?

**Comment by jonc125** [comment]
That makes sense to me. It's probably also a good time to think about splitting up what `get_equation_graph` does - iirc some of the analysis is only useful just before code generation, not pre-manipulation?

**Comment by MichaelClerx** [comment]
That's a good point the code that turns the dummies into numbers is in get_equation_graph atm but could be split off as we previously discussed...
