### ISSUE TITLE
Can we rename MetaDummy?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#129]
As far as I understand it's not a dummy itself, but something that holds information about a dummy (which itself represents either a variable or a number)

So maybe we can call it SymbolInfo or SymbolMetaData or something?

Or split it up into VariableInfo and NumberInfo ?

Am I understanding this correctly @tamuri & @jonc125 ?

**Comment by tamuri** [comment]
> As far as I understand it's not a dummy itself, but something that holds information about a dummy (which itself represents either a variable or a number)

Yes, exactly.

**Comment by jonc125** [comment]
Replaced by #148.
