### ISSUE TITLE
Rename UnitStore.get_quantity ?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#131]
Seems to return a unit rather than a quantity?

**Comment by MichaelClerx** [comment]
@skeating what do you think of the UnitStore design? Does it need to stay as it is? Come more to the foreground? Do we need to implement having multiple unitstores in cellmlmanip?

**Comment by skeating** [comment]
I have to say that I have found the UnitStore a little confusing. Need to think more about it.

Its possible we need more than one UnitStore. A model in memory has a UnitStore and you could create another instance of a UnitStore (from wherever - protocol ?) but would you need anymore.

**Comment by MichaelClerx** [comment]
I think two is enough for now.

An alternative might be that we make the UnitStore very usable, so that `fc` just creates its own UnitStore for the protocol units and generates its own pint units. There's no need for them to be in the cellmlmanip model's unit store I don't think.

**Comment by jonc125** [comment]
I like the idea of a protocol creating its own `UnitStore` - doesn't seem any reason this should live in the model.

Would they use the same underlying `pint` registry though? I'm not sure if you can compare units from different registries, even if they're both based on SI?

The aim in having two `UnitStore`s is that you don't want protocols using definitions from the model by accident, to ensure a protocol defines all the units it needs (and vv). And you don't want confusion if model & protocol define different units with the same name.

**Comment by MichaelClerx** [comment]
> Would they use the same underlying pint registry though? I'm not sure if you can compare units from different registries, even if they're both based on SI?

@tamuri do you know this? Do we need all the units to be from a single unit registry?

(Not opposed to that either, might even be easier for me in `fc` to just have a step where I resolve my unit names and definitions?)

**Comment by tamuri** [comment]
> Do we need all the units to be from a single unit registry?

I believe so - pint can't operate on units across different registries. (At least that used to be the case on the version I used but there was some discussion on the forums about allowing that)

**Comment by MichaelClerx** [comment]
OK, so I think that means we have a single unit store and need to manage our own name:unit-object mapping in FC I think.
Shouldn't be too hard I don't think. The model's unit store knows the cellml base units, so we can just build on those and store them locally inside `fc`.
Does mean that another bit of parsing the protocol now depends on having a model present (just like parsing equations in define statements)

**Comment by jonc125** [comment]
Just checked this:
```
>>> from pint import UnitRegistry as U
>>> u1 = U()
>>> u2 = U()
>>> u1.m == u2.m
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda3/envs/weblab-fc/lib/python3.7/site-packages/pint/unit.py", line 193, in __eq__
    if self._check(other):
  File "//anaconda3/envs/weblab-fc/lib/python3.7/site-packages/pint/util.py", line 629, in _check
    other.__class__.__name__))
ValueError: Cannot operate with Unit and Unit of different registries.
```
