### ISSUE TITLE
Change `units` arguments in Model methods to accept unit objects as well as strings

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#132]
To get a number in the units of a specific variable, I now need to do:

        model.get_equation_graph()
        v = model.get_symbol_by_ontology_term(OXMETA, 'membrane_voltage')
        v_meta = model.get_meta_dummy(v)
        unit = v_meta.units
        number = model.add_number(sp.Number(-80), str(unit))

might make more sense if I could use the `unit` directly? Or would that add some unforseen complication?

**Comment by MichaelClerx** [comment]
Woops, this was recently discussed in #77

@jonc125 said:
>  The possibly complex bit is as you say if you want a 'nice' name for the units, which only matters either when referring to them by name (which I don't think we should do after the parsing - much easier to refer to actual objects) or when reporting to users

and

> I agree with the suggestion for using a pint units definition when asking for conversion factors, rather than having to register one with the UnitsStore. That seems like quite a long-winded way to get the units for a variable too; passing the units field from the associated MetaDummy might be better? And perhaps a helper method Model.get_units_for(symbol) which does this?

**Comment by MichaelClerx** [comment]
So 

- [ ] Update all methods accepting units to accept unit objects
- [ ] Update them to _only_ accept unit objects, change the parsing code to ask for the unit object that matches a string itself

**Comment by MichaelClerx** [comment]
@MauriceHendrix would this cause trouble for you? We can also think about accepting both strings and unit objects

**Comment by MauriceHendrix** [comment]
as per previous whatever you do with the graph should be ok. I think should probably make it private and use only the api, as otherwsie what's the point of having an api!

**Comment by MichaelClerx** [comment]
Anyone object to having the methods accept both units and strings?

Then this would become

- [ ] Update docstrings to say units & strings are both fine

**Comment by skeating** [comment]
I think that's more usable.
