### ISSUE TITLE
Change Model.add_number to accept floats, not require sympy numbers

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#134]
I've been adding numbers using `Model.add_number(number=sp.Number(1))` but now I see that we usually use `sp.Float` ?
Is this a strict requirement? If so, we should maybe change the interface so that the method accepts a float instead of a sympy number, so that it can specify the exact number class to use itself

**Comment by jonc125** [comment]
Is this done in #148?

**Comment by MichaelClerx** [comment]
Not yet! `Model.add_number()` still expects a `sympy.Number` as its argument
