### ISSUE TITLE
Setting the initial value of a variable that was just upgraded to a state

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#135]
Say I upgrade a variable to a state variable (by replacing its defining equation).
How do I then go about setting its initial value?
Are we expecting users to manipulate the dummy info objects themselves?

**Comment by jonc125** [comment]
I'm not sure requiring users to do that would be wise! Although depends on how clear that API is. In pycml you can just do `variable.initial_value = "..."`; something equally simple in cellmlmanip would be nice.

**Comment by MichaelClerx** [comment]
It would! But we're stuck with symbols + meta-info-in-the-model because of the no subclassing thing. So it'd have to be e.g. `Model.set_initial_value(symbol, value)`

**Comment by jonc125** [comment]
I'd be OK with that API though :)

**Comment by jonc125** [comment]
Can we now close this?

**Comment by MichaelClerx** [comment]
I'm not sure! There's still no mechanism that ensures only states have initial values. Is that something we want?

**Comment by jonc125** [comment]
What about constants? I can't recall if they're kept as variables with initial values, or whether they are given assignment equations instead?

**Comment by MichaelClerx** [comment]
@tamuri ?

**Comment by tamuri** [comment]
In the method that builds the equation graph, we iterate over all the symbols on the rhs. If it's not a state or free variable (nor a number dummy), I called it "parameter" (not sure if that's right though) and add an equation assigning that symbol to its initial value - but only on the graph. It's not added as an equation to the model.

**Comment by MichaelClerx** [comment]
Hmmm! For FC and CG I would want them all to act exactly the same. So every variable has 1 defining equation that I can mess around with, and it shouldn't matter if it's a state, parameter, etc.
The whole 'defining constants through an initial value' in CellML seems like a mistake to me

**Comment by MichaelClerx** [comment]
So for the original question... We do expect users now to say `dummy.initial_value = 12` ?

**Comment by MichaelClerx** [comment]
Similarly, after turning a state into a non-state we have to remove the initial value?

(Although post-parsing this sort of thing isn't checked)

**Comment by jonc125** [comment]
Yep.
