### ISSUE TITLE
Remove Model.find_variable()

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#136]
We only use it to map MetaDummy objects to variable symbols (I think), but this could also be done with `self.name_to_symbol[dummy.name]`, I think?

@tamuri ?

**Comment by tamuri** [comment]
I think in `Model` itself, yes, it's only used to get dummy metadata given the Sympy dummy. I guess you could use `self.dummy_metadata[dummy]` directly (dummy needs to be a sympy.Dummy object). There are usages of `find_variable` in some tests which will need to be removed.
