### ISSUE TITLE
Copyright ModellingWebLab

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#14]
The license attributes the copyright to "ModellingWebLab", shouldn't we specify this a bit more accurately?

**Comment by jonc125** [comment]
Yeah, now we have a CLA signed between Oxford & UCL we should just use the same approach as Chaste.

**Comment by jonc125** [comment]
See also https://github.com/ModellingWebLab/WebLab/blob/master/LICENSE (which needs updating to 2018...)

**Comment by MichaelClerx** [comment]
> we should just use the same approach as Chaste.

Does that mean writing copyright oxford as in the web lab example?
