### ISSUE TITLE
The need for storing variable meta data in the model

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#142]
@tamuri just thinking about the way we store meta data and I'm a bit confused!

I think at the moment we have this situation:

1. The equations represent variables and numbers using sympy.Dummy objects that we create
2. Comparison of two dummies is on memory address: `(Dummy(1) == Dummy(1)) = False`, only `x = Dummy(1); (x == x) = True`
3. We store meta data in the model, instead of in the dummies themselves. As far as I understood at the time this was because sympy doesn't know how to create our types if e.g. it simplifies. But if it would do that now we'd lose the link to our dummies as well?
4. Before doing code generation or evaluation we replace our dummies with stuff Sympy can manipulate / remove / create

So now I'm wondering about step 3: Given that sympy preserves our Dummy objects, never replacing them or creating new ones etc., why can't we store stuff in a subclassed sympy.Dummy ?

**Comment by tamuri** [comment]
You're probably right (ie let's just subclass Dummy). At the time all the advice was not do to that (by Sympy authors) because it's not a use case they anticipated. All the questions on, eg, SO/Sympy forums about this always end up saying "safer to put your metadata in a dictionary".

But worth trying I think (If you have the time)!

**Comment by MichaelClerx** [comment]
I think I will, because it'd make everything a lot simpler! Thoughts @jonc125 ?

**Comment by jonc125** [comment]
Worth having a quick go at it, yes. Probably worth getting a least some of the open PRs merged first though :)
