### ISSUE TITLE
Add method to return all symbols-or-derivatives used to calculate a list of variables

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#144]
> Sure so what I'm doing there is the following:
>
>    create a list of dicts with for for each state var (for chaste output) such as name, units etc.
>
> However the chaste code has 2 different states of equations that are both preceded by only the > state vars that are used in those equations (not all ll state vars are necessarily used in both).
> 
> Alternatives could be something like
> state_vars_in([exp]) or contains_var([expr], var)

Hi @MauriceHendrix ! Was it something like this? You want to extract the state variables named in a list of expressions?

**Comment by MichaelClerx** [comment]
The use case is, you get some equations using `get_equations_for()`, and then you need to declare some of the variables used in those equations?

**Comment by MichaelClerx** [comment]
Is that right Maurice? Because that might be bit simpler (just scanning the lhs of the equations, not the rhs!)

**Comment by MauriceHendrix** [comment]
the use case is as follows:

**Comment by MichaelClerx** [comment]
@jonc125 says:

> From what I remember, pycml does the equivalent of get_equations_for to get all the equations, and then filters the full state var list accordingly using a set intersection. Not sure if the same approach would be easy with cellmlmanip as it's implemented currently?

**Comment by MauriceHendrix** [comment]
> Is that right Maurice? Because that might be bit simpler (just scanning the lhs of the equations, not the rhs!)

Actually no it's about state_vars that are used in the rhs of the set of equations. 




> @jonc125 says:
>  > From what I remember, pycml does the equivalent of get_equations_for to get all the equations, and then filters the full state var list accordingly using a set intersection. Not sure if the same approach would be easy with cellmlmanip as it's implemented currently?

but surely there is then a method to get all symbols for that set of equations no? which is basically what `find_symbols_and_derivatives` is no?

**Comment by jonc125** [comment]
Ah, yes, that's correct. The equivalent pycml method finds 'nodes' which are both equations and variables, so straight intersection works. Here you do indeed need a way to extract the symbols quickly from a set of equations.

I wonder if doing it from the graph would be more efficient than walking the equation trees?

**Comment by MichaelClerx** [comment]
Can you explain the use case again? Where are you getting the values from the variables from if they're not in the set of equations you have?

**Comment by MichaelClerx** [comment]
Maybe just point at the code :D

**Comment by jonc125** [comment]
From the ODE solver, or the tissue simulation :)

**Comment by MichaelClerx** [comment]
OK, so why do they need declaring if they already exist?

**Comment by MauriceHendrix** [comment]
```    def _format_state_variables(self):
        """ Get equations defining the derivatives including  V (self._membrane_voltage_var)"""
        # Filter unused state vars for ionic variables
        ionic_var_symbols = self._model.find_symbols_and_derivatives(self._extended_equations_for_ionic_vars)
        y_deriv_symbols = self._model.find_symbols_and_derivatives(self._derivative_equations)
        return [{'var': self._printer.doprint(var),
                 'initial_value': str(self._model.get_initial_value(var) * self._state_var_conversion_factors[var])
                if var in self._state_var_conversion_factors else str(self._model.get_initial_value(var)),
                 'units': str(self._model.units.summarise_units(var)),
                 'in_ionic': var in ionic_var_symbols,
                 'in_y_deriv': var in y_deriv_symbols}
                for var in self._state_vars]```

The return value of that is what gets passed to the jinjia2 template.

**Comment by MichaelClerx** [comment]
OK That actually looks sensible and a lot faster than doing a check for every var individually :D

**Comment by MichaelClerx** [comment]
Wondering about using the graph instead of the equations now, like @jonc125 said I think that would be faster. But inside cellmlmanip we need a method that checks a single variable.

We could do something like:

```
model.get_variables_used_by([eq.lhs for eq in self._extended_equations_for_ionic_vars])
```
?

**Comment by MichaelClerx** [comment]
@MauriceHendrix why are you editing my comments and writing stuff in them?

**Comment by MichaelClerx** [comment]
It's very confusing :D

**Comment by MauriceHendrix** [comment]
> Wondering about using the graph instead of the equations now, like @jonc125 said I think that would be faster. But inside cellmlmanip we need a method that checks a single variable.
> 
> We could do something like:
> 
> ```
> model.get_variables_used_by([eq.lhs for eq in self._extended_equations_for_ionic_vars])
> ```
> 
> ?

I guess that would be fine yes.

**Comment by MichaelClerx** [comment]
Can we come up with some sort of name for `symbols or derivatives` so we don't have to write that in all method names / docstrings etc.? For example, in Myokit I've been calling expressions referring to either a variable or a derivative "LhsExpressions"

**Comment by jonc125** [comment]
> Can we come up with some sort of name for `symbols or derivatives` so we don't have to write that in all method names / docstrings etc.? For example, in Myokit I've been calling expressions referring to either a variable or a derivative "LhsExpressions"

Hmm, good idea. Perhaps something like `term` (although that's quite generic)? LhsExpression sounds a bit wrong when you're looking for it on the RHS! I feel like there should be a standard name for this concept, but I can't think of one at present. @mirams ?

**Comment by mirams** [comment]
I think I'm a bit confused as to what we are trying to do!

**Comment by MauriceHendrix** [comment]
> I think I'm a bit confused as to what we are trying to do!

I need a way to know what state variables are being referenced in a specific set of equations.

The usages case is demonstrated by  the following example from `luo_rudy_1994.cpp`
[](https://raw.githubusercontent.com/ModellingWebLab/weblab-cg/chaste_cg/weblab_cg/data/tests/chaste_reference_models/Normal/luo_rudy_1994.cpp)
If you look `GetIIonic` and `EvaluateYDerivatives` boh start with state variable declarations followed by equations. Crucially though the state variable definitions are only there for any state variables that actually appear in the equations

so e.g.
`GetIIonic` :
        double var_chaste_interface__membrane__V = (mSetVoltageDerivativeToZero ? this->mFixedVoltage : rY[0]);
...
      double var_chaste_interface__ionic_concentrations__Ki = rY[9];
        // Units: mM; Initial value: 145.0

while `EvaluateYDerivatives` :
        double var_chaste_interface__membrane__V = (mSetVoltageDerivativeToZero ? this->mFixedVoltage : rY[0]);
....
        double var_chaste_interface__ionic_concentrations__Ca_NSR = rY[11];
        // Units: mM; Initial value: 1.8

**Comment by mirams** [comment]
Oh, I see, it isn’t that they aren’t there - they are in the y vector - just that they aren’t used so there’s no need to declare them in C++. Got you. 

`GetStateVariablesThatAppearIn(set_of_equations)` would be my name for it!

**Comment by MauriceHendrix** [comment]
> Oh, I see, it isn’t that they aren’t there - they are in the y vector - just that they aren’t used so there’s no need to declare them in C++. Got you.
> 
> `GetStateVariablesThatAppearIn(set_of_equations)` would be my name for it!
Indeed and it would also break the comparison to pycml output :)

By the way I've just realized I don't absolutely need the api I can easily get what I need like so:
```
        ionic_var_symbols = set()
        for eq in self._extended_equations_for_ionic_vars:
            ionic_var_symbols.update(eq.rhs.free_symbols)
```
I did some rudimentary timing and performance is very similar. Happy to go with that if you prefer to make it private after all.

**Comment by MichaelClerx** [comment]
:laughing:

**Comment by jonc125** [comment]
Hah! Does that get derivatives as well, or just the `Dummy` objects?

**Comment by MauriceHendrix** [comment]
> Hah! Does that get derivatives as well, or just the `Dummy` objects?

with:
(y1,y2)
-> ('_intracellular_Ca_buffering$dOTMgCdt', '_Ca_handling_by_the_SR$Vol_up')

I get:
sp.Eq(sp.sympify('x'),sp.Derivative(y1,y2)).free_symbols
->{_intracellular_Ca_buffering$dOTMgCdt, x}

**Comment by jonc125** [comment]
> > Hah! Does that get derivatives as well, or just the `Dummy` objects?
> 
> with:
> (y1,y2)
> -> ('_intracellular_Ca_buffering$dOTMgCdt', '_Ca_handling_by_the_SR$Vol_up')
> 
> I get:
> sp.Eq(sp.sympify('x'),sp.Derivative(y1,y2)).free_symbols
> ->{_intracellular_Ca_buffering$dOTMgCdt, x}

OK, so you get the state variable only. Makes sense I guess. So slightly different behaviour from the `cellmlmanip` method, but probably actually what you need! (Just not what building the graph needs.)

**Comment by jonc125** [comment]
> Oh, I see, it isn’t that they aren’t there - they are in the y vector - just that they aren’t used so there’s no need to declare them in C++. Got you.
> 
> `GetStateVariablesThatAppearIn(set_of_equations)` would be my name for it!

@mirams it wasn't the method I wanted a name for. It was something that would describe both variables (x, y, etc) and derivatives (dV/dt, du/dt, etc). We used to call these `symbols`, but in Sympy that just refers to variables so is a bit confusing! And `symbols_and_derivatives` is rather a mouthful.

**Comment by skeating** [comment]
I argued in #161 that whatever the name is, the function does not belong on the Model class as it takes any expression and returns the symbols/derivatives regardless of what the Model is. This is potentially confusing.
eg

        a = VariableDummy('a', 'second')
        b = VariableDummy('b', 'second')
        ex = sp.Add(a, b)
        syms = model.find_symbols_and_derivatives([ex])

Produces a set of symbols {_b, _a} which are not in the model. So why does the model get involved in the call !!

**Comment by MichaelClerx** [comment]
Good call! I think the units bit needs some tidying up / turning it into less of a parser tool and more of a user API :-)

**Comment by MichaelClerx** [comment]
Can we close this now? I've lost track of what's happening in this ticket :D
