### ISSUE TITLE
Determine variable equivalence before parsing equations

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#146]
The current parsing procedure is

```
    def parse(self):
        tree = etree.parse(self.filepath)

        # <model> root node - initialise the model object
        model_xml = tree.getroot()
        self.model = Model(model_xml.get('name'), model_xml.get(Parser.with_ns(XmlNs.CMETA, 'id')))

        # handle the child elements of <model>
        self._add_units(model_xml)
        self._add_rdf(model_xml)

        self._add_components(model_xml)
        self._add_relationships(model_xml)
        self._add_connection(model_xml)
```

where `_add_components` involves transpiling equations from MathML to sympy. This happens _before_ connections are determined, so that an extra step is required in which all variable references in the sympy equations are resolved, and lots of variables etc. can be removed again

It should be fairly easy to work out the variable equivalence first (this is independent of the equations, in both cellml 1 & 2), so that we can use the correct references straight away when transpiling

I think this would simplify our code and hopefully speed things up a bit too

**Comment by jonc125** [comment]
Seems sensible to me, and means the connect variables stuff (and indeed all mention of variable interfaces) can be removed from `Model`.

**Comment by MichaelClerx** [comment]
One snag: Unit conversion between components, we'd still have to remember somehow that the ref to a variable in some equations is different than the ref in other equations

**Comment by jonc125** [comment]
True. We could instead add conversion equations at parsing time, I suppose? Would that have any repercussions down the line?

**Comment by MichaelClerx** [comment]
This would make sense if we separated parsing from manipulation etc. So closing for now.
