### ISSUE TITLE
Move transpiler module outside of its own directory + simplify it

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#147]
- [x] move into cellmlmanip root module
- [x] remove unused options

**Comment by MichaelClerx** [comment]
While we're at it we could probably remove the unused `dummify=False` option

**Comment by jonc125** [comment]
Fair enough :) I suspect at one point we thought the MathML -> Sympy parsing might be useful as a standalone thing.
