### ISSUE TITLE
Possible bug in get_equations_for

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#160]
Again my simple basic ode model dsv1/dt = 1

I know I cannot get equations for symbols sv1 and t in following code 

        symbol_a = model.get_symbol_by_cmeta_id("sv11")
        equation = model.get_equations_for([symbol_a])
        assert len(equation) == 0

        symbol_t = model.get_symbol_by_name("env_ode$time")
        equation2 = model.get_equations_for(symbol_t)
        assert len(equation2) == 0

the line:         equation2 = model.get_equations_for(symbol_t)

throws an exception 'TypeError: 'VariableDummy' object is not iterable' 

surely it should return an empty list of equation

??

Bug ??

**Comment by jonc125** [comment]
`get_equations_for` expects a list, so use `equation2 = model.get_equations_for([symbol_t])`

**Comment by skeating** [comment]
thank you
