### ISSUE TITLE
Rename/move some Model functions

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#161]
1. Model. add_number()
This function merely creates a NumberDummy object. It is completely independent of the Model and adds nothing to anything. I think the name could be misleading.

I would prefer: create_number_symbol 

2. Model.check_left_right_units_equal(sympy.Equality)
This functions should be in the one of the unit classes (UnitCalculator); although that would involve passing the model/model units as an argument - so I could let it stay; but it does feel wrong. 

3. Model.find_symbols_and_derivatives(expression)
This creates a set of symbols from the list of expressions passed to it. It does not find symbols/derivatives that are in the model. Again possible misleading.  Also not sure this belongs on Model class (same as add_number) they are helper functions really.

**Comment by jonc125** [comment]
I agree with (1). (2) might be resolved as part of the units reworking cf #132. For (3) see #144.

**Comment by MichaelClerx** [comment]
I'm not sure about 1, because we already have symbols that we create via the model API, so it seems a good symmetry to me. Otherwise you have 2 types of cellmlmanip dummy, one which you can create yourself, and one which you can't

**Comment by jonc125** [comment]
Yeah, I agree about keeping it on the Model, but the name of the method could change.

**Comment by skeating** [comment]
So on this:

1. add_number()
Jonathan said: stay on Model but could change name to create_number()
Michael said: leave as-is

2. No real decision

3. Model.find_symbols_and_derivatives(expression) In #144 Michael agreed that the model was not really involved in this function but no real conclusion on what else to do with it.

**Comment by jonc125** [comment]
I think leave 2 & 3 at least as-is for now, get the units conversion stuff done, and focus on next features needed for weblab-fc. Then revisit refactorings - unless a refactoring is needed to make adding a new feature easier.

**Comment by jonc125** [comment]
@MichaelClerx @MauriceHendrix shall I rename `add_number`? Options are
- `create_number`
- `create_number_dummy`
- `create_number_with_units`
- `create_quantity`

**Comment by MichaelClerx** [comment]
I like these ones:

- add_number and add_variable
- create_number and create_variable
- create_number_with_units and create_variables

Don't really want to have an add_x and a create_y for numbers and variables. Don't like the name number_dummy

**Comment by MichaelClerx** [comment]
But I don't really mind :D

**Comment by MauriceHendrix** [comment]
> @MichaelClerx @MauriceHendrix shall I rename `add_number`? Options are
> 
> * `create_number`
> * `create_number_dummy`
> * `create_number_with_units`
> * `create_quantity`

I don't use add_number so I don't mind either way. That siad I do like `create_number_dummy` as that's what it really does it doesn't even add it to the model

**Comment by jonc125** [comment]
Well `add_variable` *does* add the created variable to the model, so is named reasonably. I think the consensus therefore is leave well alone?

**Comment by MichaelClerx** [comment]
I'm slowly coming round to `create_x` :joy: 

If it bothers @skeating I don't mind doing a find/replace on the FC code :man_shrugging: 

Up to you!

(fwiw, it doesn't create a purely free variable, it's bound to the model in that it shares its unit store)

**Comment by MauriceHendrix** [comment]
> I like these ones:
> 
> * add_number and add_variable
> * create_number and create_variable
> * create_number_with_units and create_variables
> 
> Don't really want to have an add_x and a create_y for numbers and variables. Don't like the name number_dummy

but those 2 methods doen't do the same things. One just creates (but doesn't add to the model) where as the other also adds to the model.

**Comment by MauriceHendrix** [comment]
> I'm slowly coming round to `create_x` 😂
> 
> If it bothers @skeating I don't mind doing a find/replace on the FC code 🤷‍♂️
> 
> Up to you!
> 
> (fwiw, it doesn't create a purely stand-alone number, it's bound to the model in that it shares its unit store)

True of course but if you were to search the model for it you wouldn't find it.

**Comment by jonc125** [comment]
We could in fact rename `NumberDummy` -> `Quantity`, `VariableDummy` -> `Variable`, `add_number` -> `create_quantity`?
