### ISSUE TITLE
Should we use something else instead of an `lhs` as the graph nodes?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#169]
Hi all,

I keep getting confused by networkX's graph nodes.

For example:
```
        for node in model.graph.nodes:
            print(type(node))
            print(type(model.graph.nodes[node]))
            break
```
returns
```
<class 'sympy.core.function.Derivative'>
<class 'dict'>
```

You get the same result using `for node in model.graph`.

So to get all equations you need to do crazy things like:
```
        for node in model.graph.nodes:
            equation = model.graph.nodes[node]
```

Maybe we can just introduce a `Node` class with properties like `lhs`, `rhs`, `equation` etc.?
That would also solve the problem of the node attributed being undocumented

**Comment by MichaelClerx** [comment]
Or maybe I'm just rubbish at using networkx?

**Comment by jonc125** [comment]
I don't think I know networkx well enough to give an informed comment on this! @skeating @tamuri ?

**Comment by tamuri** [comment]
`graph.nodes` is a dict, where key is anything and value is another dict (of attributes, so `Dict[Hashable, Dict]`). lhs of equation is the key, and everything else (equation itself etc.) in the attributes dict.

The nodes can be anything hashable, so no problem making your own Node class and storing the attributes therein.
