### ISSUE TITLE
Make model.equations private

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#170]
The model is responsible for the integrity of the equation list/set, so it should be private!
(And probably a set, says @jonc125 )

Seems easy, but unfortunately lots of tests use model.equations to query the internal state of the Model

**Comment by MauriceHendrix** [comment]
> The model is responsible for the integrity of the equation list/set, so it should be private!
> (And probably a set, says @jonc125 )
> 
> Seems easy, but unfortunately lots of tests use model.equations to query the internal state of the Model

Wouldn't it be possible to use model.get_equations_for (as I'm doing) and then give it the state variables?

**Comment by MichaelClerx** [comment]
Something like that would work, yes!
Just made a ticket because it involves a considerable number of changes to the code
