### ISSUE TITLE
Mismatch between equations listed by graph and returned by get_equation_for

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#188]
So for converting units of a literal constant 
x = 1 [pA]
y = 1 / x
  in [1/pA]

i.e. add_input(x, nA) should get

new_x = 1e-3 [nA]
x = new_x * 1e3 [pA/nA]
  in [pA]
y = 1 / x
  in [1/pA]

I have the following code:
```   
        eqns = self.get_equations_for([x])
        for equation in eqns:
            if equation.is_Equality and equation.args[0] == x:
                expression = sympy.Eq(new_x, equation.args[1] * conversion_factor)
                self.add_equation(expression)
                self.remove_equation(equation)
```
BUT the equation returned by get_equations_for([x]) returns Eq(_env_ode$x, 1.0)

and the equation listed by the graph is Eq(_env_ode$x, _1.0)

which is not a match and so remove_equation throws an exception. 

Surely this is a bug ??

**Comment by jonc125** [comment]
`get_equations_for` defaults to stripping units (which is most useful for code gen, which is where it's typically used), which means the equations in the graph are different from `self.equations`. So you'd want `recurse=True, strip_units=True` I think.

But if all you're using the graph for is finding the equation defining `x`, then you might be better using:
```python
for eq in self.equations:
    if eq.args[0] == x:
        # do add/remove
        break
```

If we find we're looking up the defining equation for a `VariableDummy` a lot we could always cache it in `add_equation`. But probably leave that for a separate issue/PR?

**Comment by skeating** [comment]
Thanks @jonc125 Closing this now.
