### ISSUE TITLE
Add a custom unit to registry as a Unit object

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#192]
Currently we have functions that use name and attributes of unit

    def add_custom_unit(self, units_name, unit_attributes):
        """Define a new Pint unit definition and adds it to the unit registry.
        :param units_name: name of unit to add - cannot be an existing CellML unit
        :param unit_attributes: dict object for unit
            {'multiplier': float, 'units': string, 'exponent': integer, 'prefix': string/integer}
            Not all fields necessary but 'units' must match a unit in Pint registry
        """

we need to be able to add a Unit object (obtained elsewhere) but this not as straightforward as it might seem.

**Comment by MichaelClerx** [comment]
Closing this as we've dealt with the issue in a different way :-)

(Also, if you obtain a unit object somehow you don't need to add it anymore: it's already in some registry which is either the same one you're using (which works) or a different one (in which case it won't work))

**Comment by MichaelClerx** [comment]
If you really wanted to do the 2nd case, so adding a unit that you obtained from a different repository, I guess you could do
```store2.add_unit(store1.format(unit), store1.format(unit, False))```
where the 2nd format call gives you the base units expansion
(would work as long as the unit stores both have the same base units)
