### ISSUE TITLE
get_state_symbols not working properly after conversion

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/cellmlmanip#199]
example: I added the following to test_unit_conversion.py
```
    def test_convert_state_symbols(self, aslanidi_model):
        model = aslanidi_model
        model.get_state_symbols()
        model.units.add_custom_unit('millisecond', [{'prefix': 'milli', 'units': 'second'}])
        time_variable = model.get_free_variable_symbol()
        current_units = model.units.summarise_units(time_variable)
        desired_units = model.units.ureg.millisecond

        model.convert_variable(time_variable, desired_units, DataDirectionFlow.INPUT)       
        model.get_state_symbols()
```
output:
```
====================================================== FAILURES =======================================================
____________________________________ TestUnitConversion.test_convert_state_symbols ____________________________________

self = <tests.test_unit_conversion.TestUnitConversion object at 0x05EE2670>
aslanidi_model = <cellmlmanip.model.Model object at 0x057FF4B0>

    def test_convert_state_symbols(self, aslanidi_model):
        model = aslanidi_model
        model.get_state_symbols()
        model.units.add_custom_unit('millisecond', [{'prefix': 'milli', 'units': 'second'}])
        time_variable = model.get_free_variable_symbol()
        current_units = model.units.summarise_units(time_variable)
        desired_units = model.units.ureg.millisecond

        model.convert_variable(time_variable, desired_units, DataDirectionFlow.INPUT)
>       model.get_state_symbols()

tests\test_unit_conversion.py:759:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cellmlmanip\model.py:290: in get_state_symbols
    state_symbols = [v.args[0] for v in self.get_derivative_symbols()]
cellmlmanip\model.py:274: in get_derivative_symbols
    derivative_symbols = [v for v in self.graph if isinstance(v, sympy.Derivative)]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <cellmlmanip.model.Model object at 0x057FF4B0>

    @property
    def graph(self):
        """ A ``networkx.DiGraph`` containing the model equations. """
        # TODO: Set the parameters of the model (parameters rather than use initial values)

        # Return cached graph
        if self._graph is not None:
            return self._graph

        # Store symbols, their attributes and their relationships in a directed graph
        graph = nx.DiGraph()

        equation_count = 0

        # Add a node for every variable in the model, and set additional variable meta data
        for equation in self.equations:
            equation_count += 1

            # Determine LHS.
            lhs = equation.lhs
            if not (lhs.is_Derivative or isinstance(lhs, VariableDummy)):
                raise RuntimeError('DAEs are not supported. All equations must be of form `x = ...` or `dx/dt = ...')

            # Add the lhs symbol of the equation to the graph
            graph.add_node(lhs, equation=equation)

            # Update variable meta data based on the variable's role in the model
            if lhs.is_Derivative:
                # Get the state symbol and update the variable information
                state_symbol = lhs.free_symbols.pop()
                state_symbol.type = 'state'

                # Get the free symbol and update the variable information
                free_symbol = lhs.variables[0]
                free_symbol.type = 'free'
            else:
                lhs.type = None

        # Sanity check: none of the lhs have the same hash
        assert len(graph.nodes) == equation_count

        # Sanity check: all the lhs are unique in meaning (sympy.Dummy: same name != same hash)
        assert len(set([str(x) for x in graph.nodes])) == equation_count

        # Add edges between the nodes
        for equation in self.equations:
            lhs = equation.lhs

            # for each of the symbols or derivatives on the rhs of the equation
            for rhs in self.find_symbols_and_derivatives([equation.rhs]):

                if rhs in graph.nodes:
                    # If the symbol maps to a node in the graph just add the dependency edge
                    graph.add_edge(rhs, lhs)
>               elif rhs.type in ['state', 'free']:
E               AttributeError: 'Derivative' object has no attribute 'type'

cellmlmanip\model.py:482: AttributeError
================================== 1 failed, 127 passed, 1 skipped in 11.17 seconds ===================================
```

**Comment by jonc125** [comment]
Interesting! So it is refreshing the graph, it's not just that we forgot to mark it as invalid. Maybe the graph construction expects to see the definition of an ODE before any references to dy/dt on the RHS of another equation - this probably happened by accident for all real models, but once we're adding conversion equations at the end of the list it could fail?

**Comment by MauriceHendrix** [comment]
from slack for reference:

so I can see what's causing the issue. It's processing an equation like:
Eq(_Ca_handling_by_the_SR$Ca_rel_orig_deriv, -_31.0*Derivative(_Ca_handling_by_the_SR$O_Calse, _environment$time) + ...)  when it gets to the derivative it's not in graph.nodes. That's because there is no equations for it. There only is Eq(Derivative(_Ca_handling_by_the_SR$O_Calse, _environment$time_converted, ...)

jonathan  6 minutes ago
ah, that's definitely a bug in the conversion code then!
I thought we had a test for that

maurice  < 1 minute ago
am i right in thinking it should have been _Ca_handling_by_the_SR$O_Calse_orig_deriv in the equation?

**Comment by MauriceHendrix** [comment]
maurice  4 minutes ago
however if I look at [eq.rhs.args for eq in self.equations if isinstance(eq.lhs, sympy.Derivative)] I get a list with lots of entries and one is:
(-_31.0*Derivative(_Ca_handling_by_the_SR$O_Calse, _environment$time), (-_Ca_handling_by_the_SR$i_rel + _Ca_handling_by_the_SR$i_tr)/(_2.0*_Ca_handling_by_the_SR$Vol_rel*_membrane$F))

maurice  4 minutes ago
hence -_31.0*Derivative(_Ca_handling_by_the_SR$O_Calse, _environment$time) which doesn't match -Derivative(_Ca_handling_by_the_SR$O_Calse, _environment$time)

jonathan  2 minutes ago
Ah, so it's not recursing, only looking at the top-level children of the RHS?

maurice  1 minute ago
yup

jonathan  1 minute ago
Quick bodge could be to use find_symbols_and_derivatives I guess, though we should update the test to fail first really

maurice  < 1 minute ago
I guess the test just test models where it happens tobe he top level

maurice  < 1 minute ago
I'll use find_symbols_and_derivatives and update the test as well

**Comment by MauriceHendrix** [comment]
Or better, eq.rhs.atoms(Derivative) should give you just any derivatives on the RHS I think: https://docs.sympy.org/1.5.1/modules/core.html#sympy.core.basic.Basic.atoms



maurice  10 minutes ago
.atoms() doesn't work it goes to far and pulls apart the derivative

jonathan  9 minutes ago
Hmm, it says if you pass in a type that it should work with non-atomic types

jonathan  8 minutes ago
It uses Function as an example - I'd be surprised if Derivative was that different?

maurice  7 minutes ago
aah yes but that pulls out only the derivatives

jonathan  7 minutes ago
That's what we want in _replace_derivatives though :slightly_smiling_face:

maurice  4 minutes ago
that's a good point actually
