### ISSUE TITLE
Test simple ODE solving

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/cellmlmanip#2]
Try using [lambdify](http://www.sympy.org/scipy-2017-codegen-tutorial/notebooks/22-lambdify.html) to convert a system of equations to a Python function and solve with scipy's ODE solvers.

- [x] dV/dt = 1, V(0) = 1
- [x] dx/dt = 1, dy/dt = -1, x(0) = y(0) = 1
- [x] dx/dt = -y, dy/dt = x, x(0) = 0, y(0) = 1
- [ ] dx/dt1 = -y, dy/dt2 = x, t1 = t2, x(0) = 0, y(0) = 1

The last case checks whether connecting 'time' across components will work naturally. To check connecting V we could use:

- [ ] dV/dt = 1, derived = V1 * 2, V1 = V, V(0) = 1

Child of https://github.com/ModellingWebLab/project_issues/issues/34

**Comment by tamuri** [comment]
I’ve pushed some work-in-progress related to this issue as PR #19 

The goal was to determine the steps required to take ODEs defined in MathML, convert them to SymPy expressions and then use those expressions in callbacks suitable for solving using SciPy [odeint()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html).

Does anyone have ideas on how best to deal with systems that include an equality that is not an ODE. An example is ODEs from two component that are connected by a third equation e.g. example 4:

```
⎡           d                d            ⎤
⎢ t₁ = t₂, ───(x(t₁)) = -y, ───(y(t₂)) = x⎥
⎣          dt₁              dt₂           ⎦
```

Is there any way simplify these in SymPy other than taking the `t₁ = t₂` relation to substitute symbols in all expressions using `exprs.subs({t1: t2})`?

Especially interested of the case when `t₁` and `t₂` are units of different multiples (e.g. `t₁` seconds and `t₂` milliseconds).

**Comment by mirams** [comment]
Here we do want to substitute in so that we have the same time variable everywhere I think.

In other cases we might want to solve a Differential-Algebraic Equation (DAE) system. There are dedicated solvers for these (that aren't just ODE solvers) where constraints/extra equalities can be explicitly included. I played around with these for ion channel systems in https://chaste.cs.ox.ac.uk/trac/ticket/2715 

I'm not sure how you would automatically tell the difference between the two from just the equations. Perhaps if you have a DAE system within a single CellML component then it really is a DAE system, and otherwise it is an ODE system that needs substitution? Or does CellML have a way of specifying DAE system Jon?

**Comment by jonc125** [comment]
CellML doesn't have any explicit indication for a DAE system, you have to infer it from the system of equations (and indeed the overall system for the whole model - it might not live just within one component). Not sure if there's anything in SymPy that would help with that?

Equations that arise from connections are the tricky case as Asif says. If there are no unit conversions, then conceptually the variables in each component are actually "the same variable" and substituting is probably the "right thing" to do. I was just hoping that SymPy's simplification would do this for us automatically 😞 

However, the story with unit conversions is more complicated, since there is then an implicit equation. This is particularly nasty when you have unit conversions for the independent variable, as you then need to modify some of your ODEs so they all use the same variable or the solver gets things wrong. This is coded manually in the Web Lab at present; I was hoping we wouldn't have to replicate all those checks & manipulations!

@MichaelClerx @nickerso are you aware of any tricks for this?

**Comment by nickerso** [comment]
no, sorry! hadn't even considered unit conversions for the independent variable... Convert all variables and math to base units before attempting any simplification, substitution, or solving?

**Comment by jonc125** [comment]
Converting to base units isn't necessarily ideal because you end up with lots of very small numbers, which increases the impact of floating point numerical error...

**Comment by jonc125** [comment]
(Really you ought to non-dimensionalise the model before solving, but...)

**Comment by jonc125** [comment]
As discussed today, we probably want to solve these connection issues in the context of the actual code generation we're going to use to solve simulations.

**Comment by tamuri** [comment]
solving is handled by weblab-cg
