### ISSUE TITLE
Improve how initial values and parameters are handled

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/cellmlmanip#201]
Basically, once parsing is done, initial values should only appear for state variables, and everything else should be represented as actual assignment equations. To support this, we can adapt how we store equations internally to the `Model` so we have some extra lookup maps.

* [x] Store a map from LHS to equation, so it's quick to look up the definition of a variable
    * Where the LHS is a derivative, also add the dependent variable in the map? Or just in the parser? Or in a separate map? I think a separate map, but open to suggestions.
* [x] `Model.add_equation` should maintain these maps (similarly `remove_equation`)
* [x] After the parser has processed all equations, it goes through all variables with initial_value
    * If they're in the 'defined by ODE' map, it leaves them alone
    * Otherwise it adds a defining equation with just a number on the RHS, and removes the initial_value
* [x] Update `get_derivative_symbols` to use the ODE map
* [x] Don't add excess metadata to graph (#180), but *do* ensure parameters are properly marked (so every equation where RHS is just a number should result in LHS marked as parameter)
* [x] Use the maps in units conversion logic, for quicker lookups of defining equations
* [x] And a related minor refactoring: remove the `get_initial_value` method, since you can just do `symbol.initial_value`

Possibly subsumes (some of) #135 and #120. Maybe #169 #130 #180?

I don't think we necessarily want to prioritise doing this before the next bits of weblab-fc work - unless we think it'll make doing that work easier!

Thoughts @skeating @MauriceHendrix ?

**Comment by MauriceHendrix** [comment]
should we remove `get_initial_value()` since it no longer seems to work?
