### ISSUE TITLE
Allow UnitStore to share a registry with an existing unit store

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#214]
- [ ] So that the pint registry is the same, but the names are completely separated
- [ ] When parsing a model it should be possible to pass in an existing unit store

**Comment by MichaelClerx** [comment]
It seems the unit registry is responsible for maintaining the names. So for example if we create a unit `mm = 1000 * meter` then `mm` gets added to the registry. This means that later we can ask the registry to parse strings like `5 * mm`. So having a shared registry would mean we can't separate unit namespaces.

**Comment by MichaelClerx** [comment]
So now think it'd be better to just have distinct unit registries, and to just use quantities everywhere (comparing quantities from different registries is allowed)

```
#!/usr/bin/env python3
import cellmlmanip
import cellmlmanip.units

import os

import pint

path = os.path.join('cellmlmanip', 'data', 'cellml_units.txt')
r1 = pint.UnitRegistry(path)
r2 = pint.UnitRegistry(path)

c1 = r1.candela
c2 = r2.candela

print(c1, type(c1))
print(c2, type(c2))

#print(c1 == c2)

q1 = 1 * c1
q2 = 1 * c2

print(q1 == q2)
```

**Comment by jonc125** [comment]
That sounds like a workable plan!

**Comment by MichaelClerx** [comment]
I thought so, but seems `pint` isn't set up for that:

```
#!/usr/bin/env python3
import cellmlmanip
import cellmlmanip.units

import os

import pint

path = os.path.join('cellmlmanip', 'data', 'cellml_units.txt')
r1 = pint.UnitRegistry(path)
r2 = pint.UnitRegistry(path)

r1.define('abc=meter*0.2')
r2.define('xyz=meter*0.2')

u1 = r1.abc
u2 = r2.xyz

print(u1, type(u1))
print(u2, type(u2))

q1 = 1 * u1
q2 = 1 * u2

print(q1, type(q1))
print(q2, type(q2))

print(q1 == q2)
```

**Comment by jonc125** [comment]
Drat! Do we need to share a registry after all, and just make `UnitStore` prefix unit names with a uuid say before defining them in pint's registry?

**Comment by MichaelClerx** [comment]
Yeah if we run a regex over each definition the user passes in to turn e.g.
``mm = meter * 1000`` into ``special_mm = special_meter * 1000``

This will make error output harder to read though, as the user will see all the weird names
