### ISSUE TITLE
Units or unit?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#223]
We've currently got both: E.g. ``VariableDummy.units`` returns a ``Unit`` object (not a ``Units``) object.

In cellml it's called units, in pint it's called unit, so there's some case for either.

Should we be consistent and pick one? My preference is unit, without an s

**Comment by jonc125** [comment]
The FC protocol language uses 'units' following CellML...

**Comment by jonc125** [comment]
I think you'd normally say 'the units of x'?

**Comment by mirams** [comment]
I prefer units like this dictionary definition:
> A unit of measurement is a fixed standard quantity, length, or weight that is used for measuring things. The litre, the centimetre, and the ounce are all units.

**Comment by MichaelClerx** [comment]
? OK so `volt` is a unit, then `add_unit('volt')` makes sense, right?
And then the unit object associated with a variable should be `x.unit` because it refers to a unit object?

**Comment by mirams** [comment]
I would say add_units('millivolt per microsecond') though. But I don't really care, spend time on important things whilst you are all there!!

**Comment by MichaelClerx** [comment]
Just want to be consistent :D
