### ISSUE TITLE
Maintain a cmeta_id to symbol mapping

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/cellmlmanip#228]
Looking up a symbol by ontology term relies on lookup by cmeta_id, and we do a lot of these in Web Lab logic (and several in Chaste code gen too). But lookup by cmeta_id currently requires iterating over all symbols. Looking up in a dict would be better. We just need to ensure the map can't get out of sync too easily - at present updating cmeta ids is just an operation on the `VariableDummy` objects so the `Model` doesn't know about it. To fix this we'll need 2 new methods on `Model`:
* [x] `transfer_cmeta_id(self, from, to)` moves an ID from one variable to another. Used in units conversion code. Just needs to move the `cmeta_id` from `from` to `to` and update that entry in the map.
* [x] `add_cmeta_id(self, var)` adds an ID to a variable that doesn't have one. It can be implemented as `var.cmeta_id = self.get_unique_cmeta_id(var.name.replace('$', '__'))` (and add to the map)

**Comment by MichaelClerx** [comment]
To make it safe, we have to stop users from inadvertently changing a cmeta id.
Three options:

1. Make a `cmeta_id()` method. My preferred option as it's clear to everyone that it exists and what it does.
2. Use the @property decorator to make `cmeta_id` a read-only property. Document this in the class's main docstring.
3. Use @property but go all out and let users set it and then automatically update the model (requires to have a link to the model in each VariableDummy)

**Comment by MichaelClerx** [comment]
We've already got a `rdf_identity` property in there, which is a plus for option 2 I guess?

**Comment by jonc125** [comment]
With the `rdf_identity` property there's probably very little need for external code to be reading the `cmeta_id`, so could make it an internal property that only the `Model` sets?

**Comment by MichaelClerx** [comment]
ok!

**Comment by MichaelClerx** [comment]
Then again, that's a bit weird, we've got all these methods to transfer cmeta ids but the user isn't allowed see them?

**Comment by MichaelClerx** [comment]
Hmmmm, there's also a lot of RDF manipulation going on, but the documentation simply says "further meta data" is stored in the RDF graph. How do I find out what meta data and whether or not I need to do anything with this when updating cmeta ids?

**Comment by jonc125** [comment]
The point of transferring IDs is that the metadata then doesn't need updating. You're just changing the variable it points at.

We could have a readonly public property to let people read the ID, just not (easily) set it. But it's really the RDF term that Web Lab use cases need; the ID is just internal detail.

**Comment by MichaelClerx** [comment]
Yup! But searching for places where the _cmeta_id gets checked I found some places that manipulate the RDF graph... Will try to work around.

**Comment by jonc125** [comment]
I can't see anything in the cellmlmanip core code that wouldn't be covered by the proposed methods. What cases have you found?

**Comment by MichaelClerx** [comment]
Just removing the triples when a variable gets removed. It turns out not to matter for this ticket, but I was trying to understand what the code did / what the implications were!

**Comment by MichaelClerx** [comment]
Should we make ``get_symbol_by_cmeta_id()`` private as well then? There's quite a few tests that use it but not sure that they need to

**Comment by jonc125** [comment]
It's a known CellML thing, so other users might well want it for different reasons. No particular reason to hide it I think.

**Comment by MichaelClerx** [comment]
Should `add_cmeta_id` silently ignore the case where the variable already has a cmeta id? Or raise something?

**Comment by jonc125** [comment]
Good question. For FC use cases at present we'd call it just after discovering that the variable doesn't have one. So could make it a no-op if an ID exists, and avoid the check before calling.
