### ISSUE TITLE
Symbol, variable, or variable dummy?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#230]
Throughout the model class, we've got lots of methods that take arguments called ``symbol`` (and methods like ``get_symbol_by_X``), and a few ``var``s and ``variable``.
What is meant in each case is a ``VariableDummy`` (so not just any old numpy symbol, or a NumberDummy (which is also a symbol)).
(There's also add_variable(), which returns a VariableDummy)

Should we maybe change all these to something consistent, e.g. ``variable`` ?

**Comment by jonc125** [comment]
Using `variable` everywhere makes sense to me.

**Comment by MauriceHendrix** [comment]
Not particularly pressing but yes sure it would be more consistent.
