### ISSUE TITLE
Expose component/variable naming separator and make `fc` use it

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#234]
https://github.com/ModellingWebLab/weblab-fc/blob/master/fc/code_generation.py#L109-L121

**Comment by jonc125** [comment]
Or should the `get_unique_names` be in cellmlmanip? Presumably chaste_codegen needs to do something similar @MauriceHendrix ?

**Comment by MichaelClerx** [comment]
I think that could serve as a useful basis for many code generators yeah.

Although in Myokit I had to add a `Model.reserve_unique_names(list)` method as well to stop the generated names overlapping with keywords in some languages.

And even then for some languages / formats I just reimplemented a custom unique name scheme :D

**Comment by MauriceHendrix** [comment]
I don't think I use that tbh the few symbols I create are going to be unique since they don't have a component name

**Comment by MichaelClerx** [comment]
OK, code in FC is now updated
