### ISSUE TITLE
Make Model._get_unique_name public

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#235]
Used in `fc`: https://github.com/ModellingWebLab/weblab-fc/blob/master/fc/parsing/actions.py#L937

**Comment by MichaelClerx** [comment]
Thoughts @jonc125 @MauriceHendrix @skeating ?

**Comment by jonc125** [comment]
Sounds good to me. Don't see any reason to keep it private!

**Comment by MauriceHendrix** [comment]
I don't see why not tbh
