### ISSUE TITLE
Add `model.is_state(variable)`

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#236]

**Comment by MichaelClerx** [comment]
Sorry I meant to ask for opions on this one instead of #235 :man_facepalming: 

@jonc125 @MauriceHendrix @skeating ?

**Comment by MauriceHendrix** [comment]
you could just do `variable in model.get_state_symbols()` ?

**Comment by MichaelClerx** [comment]
That's a list creation + sorting though. Not very efficient for a simple query like this?

**Comment by MauriceHendrix** [comment]
I see the way I see it 4 options:
- cache the result inside model, just like what happens with the graph
- cache in your code e.g. `state_vars = model.get_state_symbols() | ... variable in state_vars` this is what I do currently
- add the method as you describe, I'm not against it just wondered if it's really necessary
- give VariableDummy's and attribute `is_state_var`  or something like that

**Comment by jonc125** [comment]
What's the push for adding another method though?

Though we could do it very cheaply without considering the graph, actually, because we now have the definition maps - so we just need to check if the variable is in the ODE one. Which might be worth implementing as a helper method since the map is private.

Which I think means I'm +1 for doing this!

**Comment by jonc125** [comment]
> What we could also do is is what we do with the graph: i.e. caching it inside the model, might be nice for consistency.

I'd only be inclined to cache the state variable list if profiling showed creating it repeatedly was a noticeable hit on performance. Since there's also a memory and complexity hit from caching.

**Comment by MauriceHendrix** [comment]
> > What we could also do is is what we do with the graph: i.e. caching it inside the model, might be nice for consistency.
> 
> I'd only be inclined to cache the state variable list if profiling showed creating it repeatedly was a noticeable hit on performance. Since there's also a memory and complexity hit from caching.

I'm not sure what FC is doing but for chaste_codegen it wouldn't make any difference
