### ISSUE TITLE
Design intemediate representation & family of modules

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/cellmlmanip#24]
Some thoughts from Rob Blake, Melodee author:
- SymPy's ternary if expression
    - Has issues for doing things like automatic differentiation
    - Also, if you have intermediate variables that are only needed within one block, this can't be done with ternarys
    - So he used his own SSA representation for if blocks
- Units
    - He thought SymPy's was too heavyweight for what he needed, hence built his own
    - One nice feature is its 'sensible' printing of units
- Strongly advocates for working with sets of variables. This is something we'd do anyway; it's what pycml does
- Code generation
    - Version '2' of Melodee tried the templating approach. Found it got very messy if the 'code' part became complicated. E.g. for doing Markov models with Rosenbrock methods, which requires auto-differentiating the Jacobian and assigning things in a strange order.

**Comment by MichaelClerx** [comment]
Can we close this now?
