### ISSUE TITLE
Model.get_free_variable() in a model without ODEs

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#262]
@jonc125 @MauriceHendrix  I'm running into a problem with cellmlmanip saying "No free variable set in model." after I change the only ODE in a model to be a regular equation. 

It happens because, without any ODEs, cellmlmanip is no longer able to detect the free variable.

Did you come across this? What's the strategy for dealing with this? Should we change get_free_variable() to return any old undefined variable if there's no ODEs ?

**Comment by jonc125** [comment]
weblab-fc tries to work around this by adding time back into the model graph if modifications get rid of all ODEs, with `self.model.graph.add_node(time_variable, equation=None, variable_type='free')`

Where does your call hitting the error happen?

I think cellmlmanip *should* return an error if you ask for the free variable and there isn't one!

**Comment by MichaelClerx** [comment]
Handling defines etc. can remove the time variable too. Should we add a context manager that maintains the time variable then? Or define a local "replace_equation" method that takes care of it?

**Comment by MauriceHendrix** [comment]
I haven't tried models without any ODEs actually. How does the free_variable thing work actually is it just looking for dx/d<free_var> or does it scour the model for exactly 1 variable which is used but not defined? In other words if that new equations had time in it would it still work?

**Comment by jonc125** [comment]
So the initial call to `get_free_variable` in `_purge_unused_mathematics` is failing?

**Comment by jonc125** [comment]
Possibly we could make the `graph` method add any variables not appearing in equations to the graph, and set their type as free? Though may want some check that only have one free variable?

**Comment by MichaelClerx** [comment]
> So the initial call to get_free_variable in _purge_unused_mathematics is failing?

yup!

**Comment by MichaelClerx** [comment]
> I haven't tried models without any ODEs actually. How does the free_variable thing work actually is it just looking for dx/d<free_var>

Exactly

**Comment by jonc125** [comment]
Or we could resolve this just in weblab-fc, by storing the free variable in the interface before making modifications. Though we'd need to update it if converted in any of 3 places (`_convert_time..., _add_input..., _convert_output...`).

**Comment by MichaelClerx** [comment]
> Or we could resolve this just in weblab-fc, by storing the free variable in the interface before making modifications. Though we'd need to update it if converted in any of 3 places (`_convert_time..., _add_input..., _convert_output...`).

Yeah, that's why I was thinking of having either a context manager (stores and restores time) or a method to replace equations (does same + remove old eq, add new eq)

**Comment by MichaelClerx** [comment]
(all in FC, not in cellmlmanip)

**Comment by jonc125** [comment]
I think it's just `model.convert_variable` that you need to wrap.

Unless the protocol author tries to be really nasty and creates their own new variable to be time, with no relation to the original time in the model, deletes all old ODEs and creates new ones... So maybe `_add_or_replace_equations` also needs to spot the free var in any added ODE and check against the cached free variable?

**Comment by MichaelClerx** [comment]
All you need to do is redefine an ODE to not be an ODE, for a model with a single ODE

**Comment by jonc125** [comment]
That's enough to lose time, yes. What I'm talking about is if you start caching time you need to track modifications that change which variable represents time.

**Comment by MauriceHendrix** [comment]
If you had a model that didn't have any ode's to begin with (e.g. you modified the 1 ode model before loading it in) how would you know time?

**Comment by jonc125** [comment]
It wouldn't exist. You'd have to create it if you wanted it.

**Comment by MichaelClerx** [comment]
You wouldn't! So we might have to add a test for that, and make sure it gives a user-readable error message

**Comment by MichaelClerx** [comment]
What about annotations? Could we use the time annotation when no ODEs are set? And if ODEs are set, should we check they integrate w.r.t. the variable annotated as time (if present) ?

**Comment by jonc125** [comment]
Well, cellmlmanip probably shouldn't treat the time annotation as special. But weblab-fc could. So a simpler approach might well be for `_purge_unused_mathematics` to grab the variable annotated as time if `get_free_variable` gives an error. Maybe even create it if it doesn't exist?

A post-manipulation sanity check could check that if a variable is annotated as time, this is also connected to the free variable in any ODEs. But that's tricky to assess, because the connections aren't explicit - there may be units conversions! So I'm not sure this is worth doing.

**Comment by MichaelClerx** [comment]
ok, will try doing something minimal that makes the tests work for now

**Comment by MichaelClerx** [comment]
I'm guessing the user shouldn't be allowed change the time variable, because we have special syntax to e.g. change its units. What should that syntax do if you then pick a different variable and make all derivatives be w.r.t. that?

**Comment by jonc125** [comment]
Sob pitifully :)

It depends on how much we want to try to cope with bizarre usage. Being pragmatic, all cases we're likely to see will have time annotated in the model and manipulated derivatives will still be wrt that (perhaps with units conversions). We could relatively easily give an error if a `define` creates an ODE where the independent variable isn't the RDF term oxmeta:time, as a sanity check?

**Comment by MichaelClerx** [comment]
Yeah I'm happy with that. Few minor points:

1. Not sure if cellmlmanip currently checks that there's only 1 free variable #263
2. Have added a check that there's at least 1 derivative into FC, so that we can get a free variable from there. Not entirely sure if we should be using annotations, because we don't _officially_ tie anyone to oxmeta?

**Comment by jonc125** [comment]
On (2) I think it would be reasonable to fall back to oxmeta:time if there isn't an ODE, since we do also use oxmeta:state_variable for state vars, so that ontology is already special. Since we can create models with no ODEs, it'd be consistent to allow such as inputs. But it's a pretty minor point, and has never been an issue in practice thus far for WL1...
