### ISSUE TITLE
Use consistent argument ordering for unit conversions?

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/cellmlmanip#266]
Currently we have a mix of `to_units, from_units` (e.g. `UnitStore.get_conversion_factor`) and `from_units, to_units` (e.g. `UnitStore.convert`). We should pick one!

@MichaelClerx and @jonc125 prefer `from, to`. However the main method used by external code is probably `get_conversion_factor` so this change would impact @MauriceHendrix .

Should we make the change?

**Comment by MichaelClerx** [comment]
I'd say Yes :-)

**Comment by MauriceHendrix** [comment]
In general I'd say sure makes sense
