### ISSUE TITLE
Add model property to VariableDummy

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#271]
- A variable dummy is tied to a model: it's not possible to re-use a variable dummy with a different model (e.g. a model stores all variable dummies it has when creating them, and they have a model-specific order_added property)
- I've got some use cases where we pass dummies around, but not necessarily the model object https://github.com/ModellingWebLab/weblab-fc/pull/158#discussion_r413871468

Thoughts @jonc125 @MauriceHendrix ?

**Comment by MauriceHendrix** [comment]
There are cases where I need to know if something is constant and for that i need to inspect the model as well.

**Comment by jonc125** [comment]
Sounds like as well as the `model` property on `VariableDummy`, having an `is_constant(var)` method on `Model` (to parallel `is_state`) would be useful?

**Comment by MauriceHendrix** [comment]
definately
