### ISSUE TITLE
Remove `set_lhs_units_from_rhs`

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#273]
I don't think we should have this method in cellmlmanip.

- We have a convert_units method that assumes all variables are in the correct units. When it "changes" a variable's units, it creates a new variable dummy an updates all references to the old variable dummy. No variable dummy units are changed post-construction
- Now we have this set_lhs_units_from_rhs method that assumes the units are wrong, changes a variable dummy's units post-creation, without changing any of the other equations

I don't want to mix these two approaches within the same piece of software.

To create a variable that will have units appropriate for a given RHS, using `set_lhs_units_from_rhs` you'd have to:
1. Create a variable in some, presumably wrong units
2. Add an equation with mismatching units
3. Fix the mismatch by calling `set_lhs_units_from_rhs`

Instead why not
1. Deduce the correct units from the rhs, fixing issues if needed, by calling `convert_expression_recursively(rhs, None)`
2. Add the variable in the correct units
3. Add a correct equation

**Comment by jonc125** [comment]
If we're adding/adapting equations at the same time as creating variables, that is possible and fine by me. I thought we'd need the `set_...` approach because variable creation was a separate earlier phase.

**Comment by MichaelClerx** [comment]
Do we even _want_ internal conversion within an RHS if we're deducing the units from an RHS?

It would mean plus stops being commutative:
```
output x
optional x default 0 :: mV + y_in_volt
```
and
```
output x
optional x default y_in_volt + 0 :: mV
```
create an x in mV and in V respectively

**Comment by jonc125** [comment]
You should get the same simulation results though. And you need it to support `original_definition`, since that part of the equation might well be in different units from the part the protocol adds.

**Comment by MichaelClerx** [comment]
It's even worse with `original_definition`! I can now write `x = original_definition` and the "original definition" might have within-equation unit conversion applied to it that the original definition did not

**Comment by jonc125** [comment]
It's unfortunate that CellML 2 decided to take the opposite approach to pycml here! In my defence, I've always said unit conversions should take place within equations, or modellers should write their units correctly :) If they don't, they shouldn't complain if unexpected things happen!

**Comment by MichaelClerx** [comment]
How about we use within-rhs conversion if we're updating variables, but if we set an LHS unit depending on what the RHS is, then we expect the RHS to be consistent at least?

**Comment by jonc125** [comment]
Or we could tweak the implementation of original_definition slightly. It occurs to me that we could add a new variable to which the original RHS is assigned, with units of the original LHS (set by the model, so known), and then reference that variable in the new RHS. That reference would have known units, and there would be no danger of within-equation conversion of the original definition.

**Comment by jonc125** [comment]
I want to allow use cases such as adding an extra transmembrane current, where you would naturally add that current in the protocol's preferred current units, but the model may well be using different units, and you want to allow writing `i_total = new_current + original_definition`.

**Comment by MichaelClerx** [comment]
OK.

For adding new variables I want to follow approach 2 from above:

Instead why not
1. Deduce the correct units from the rhs, fixing issues if needed, by calling `convert_expression_recursively(rhs, None)`
2. Add the variable in the correct units
3. Add a correct equation

where step 1 will involve calling some method that fixes the RHS if needed, and step 2 may involve dividing by time units (in FC)

**Comment by MichaelClerx** [comment]
> It's unfortunate that CellML 2 decided to take the opposite approach to pycml here! In my defence, I've always said unit conversions should take place within equations, or modellers should write their units correctly :) If they don't, they shouldn't complain if unexpected things happen!

The eventual CellML 2 consensus was that the validity of the mathematics was a separate issue to the validity of the CellML document, and that the specification only concerned itself with the validity of the CellML document.

(So a valid cellml doc can say 2 == 3, there's nothing in the cellml spec that says it can't, but there's also nothing in the spec that says tools should not complain when they encounter such a document. It makes sense, because if we require the mathematics to make sense then validating a cellml document would entail deciding if any given mathematical statement is self-contradictory or not)

But thinking about that, we probably shouldn't have point 3.28.3 (the units don't affect the maths) in the new spec, as it's a statement about the interpretation of the mathematics. I've flagged this up for the next spec https://github.com/cellml/cellml-specification/issues/326

**Comment by MichaelClerx** [comment]
Personally I would expect software to either (1) ignore all units (Myokit does this), or (2) assume the units have meaning and complain if they're inconsistent.
The middle ground where the software silently fixes issues makes me very uneasy, especially since I'm certain the model authors did not write their original code with unit-correcting software in mind

**Comment by MichaelClerx** [comment]
> Do we even _want_ internal conversion within the RHS if we're deducing the units from the RHS?
> 
> It would mean plus stops being commutative:
> 
> ```
> output x
> optional x default 0 :: mV + y_in_volt
> ```
> 
> and
> 
> ```
> output x
> optional x default y_in_volt + 0 :: mV
> ```
> 
> create an x in mV and in V respectively

@jonc125 as far as I can tell sympy re-orders terms in an Add to get some kind of consistent order. This ordering will then determine the units of our LHS. Do we really want this?

**Comment by MichaelClerx** [comment]
> Do we even _want_ internal conversion within the RHS if we're deducing the units from the RHS?
> 
> It would mean plus stops being commutative:
> 
> ```
> output x
> optional x default 0 :: mV + y_in_volt
> ```
> 
> and
> 
> ```
> output x
> optional x default y_in_volt + 0 :: mV
> ```
> 
> create an x in mV and in V respectively

@jonc125 as far as I can tell sympy re-orders terms in an Add to get some kind of consistent order. This ordering will then determine the units of our LHS. Do we really want this?

**Comment by jonc125** [comment]
> @jonc125 as far as I can tell sympy re-orders terms in an Add to get some kind of consistent order. This ordering will then determine the units of our LHS. Do we really want this?

I think that's fine. It's not ideal, but it's much easier than pycml's more intelligent approach!
