### ISSUE TITLE
Do a public release

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/cellmlmanip#288]
This requires:
- [x] Figuring out the PyPI process
- [x] Deciding on a suitable version number
- [x] Merging `develop` to `master`
- [x] Tagging a release on GitHub
- [x] Uploading to PyPI

**Comment by MauriceHendrix** [comment]
her'se a good tutorial on the release process: https://packaging.python.org/tutorials/packaging-projects/

I've just made a pr #292 to update some documentation in preparation

**Comment by MauriceHendrix** [comment]
Release 0.2.0 now out!
