### ISSUE TITLE
Use the logging module to report warnings

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/cellmlmanip#3]
Instead of just printing :)

**Comment by MichaelClerx** [comment]
This one?

https://docs.python.org/3/library/logging.html

**Comment by MichaelClerx** [comment]
Out of curiosity, what's the use case for printing outside of a debugging context?

**Comment by jonc125** [comment]
Warning the user about non-critical errors, mostly. So things that still let a simulation run, but may explain why the results aren't as expected.

**Comment by tamuri** [comment]
now uses logging
