### ISSUE TITLE
setup.py is missing dependencies

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#30]
This means my [plan to install it via git into fccodegen](https://github.com/ModellingWebLab/fccodegen/blob/66c2046cb9b6db5c3ef3d95d72bb32fed953dcee/dev-requirements/base.in#L1) (until pip can do it) doesn't work.

Can we add the dependencies to setup.py? Preferably unpinned? @jonc125 @tamuri ?

**Comment by jonc125** [comment]
Sounds good!

**Comment by MichaelClerx** [comment]
Seems to be working now!
