### ISSUE TITLE
Cellmlmanip is incompatible with newer versions of sympy

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#31]
It's currently pinned to 1.1.1 (Jul 27, 2017) but fails with 1.2 (Jul 9, 2018) and 1.3 (Sep 14, 2018), both of which are pip installable stable releases. 1.3 adds an additional deprecation warning

**Comment by jonc125** [comment]
Is the new API better?

**Comment by jonc125** [comment]
Hmm, that doesn't look particularly promising!

**Comment by MichaelClerx** [comment]
It does seem to say they've only deprecated stuff, so maybe this isn't the cause of the issue we're seeing?

**Comment by MichaelClerx** [comment]
@tamuri is this fixed in the new branch?

**Comment by tamuri** [comment]
Haven't upgraded as yet. I'll work on it next week, I think it'll break some of the expression printing, so be prepared!

**Comment by MichaelClerx** [comment]
ping!

**Comment by tamuri** [comment]
I know there's discussion about pinning packages at all but I've updated the packages (Sympy required some changes to cellmlmanip)

https://github.com/ModellingWebLab/cellmlmanip/commit/da64d7f3e9c0b54e6eca44511fda7cf6a661e9f5 (feature/update-packages)

**Comment by MichaelClerx** [comment]
Thanks!
