### ISSUE TITLE
Jacobians / Partial derivatives would be nice

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#35]
For our ode systems `dy/dt = f(y, p, t)` (where `y` is the state, `t` is time, and `p` is a parameter vector), it'd be good if we could at some point also get `df/dy` (for integration) and `df/dp` (for fitting)

@jonc125 is this in (long-term) scope?

**Comment by jonc125** [comment]
I think this is (reasonably!) easy to do in sympy. A bit of googling finds https://github.com/bjodah/pyodesys which may be worth using/stealing ideas from?

**Comment by jonc125** [comment]
Though also worth saying that WL1 didn't bother with symbolic Jacobians for simulation, given that our Frontiers paper found this caused some models to break and you couldn't easily predict which.

**Comment by mirams** [comment]
Gets back to the old automatic l'Hopital rule type alterations, might be something SymPy could actually do for us too?

**Comment by MichaelClerx** [comment]
Is this all moved to chaste-codegen now?

**Comment by jonc125** [comment]
I suspect so, except possibly the fitting bit? @MauriceHendrix the pyodesys link above might be useful?

**Comment by MauriceHendrix** [comment]
@jonc125 @MichaelClerx  chaste_codegen does indeed do jacobians (they're built-in in sympy actually!) no fitting that I'm aware of (yet)
