### ISSUE TITLE
Error if component contains units

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#358]
We're not supporting this (it will be gone in CellML 2), so should raise error if found

```
<?xml version="1.0" encoding="UTF-8"?>
<!-- CellML Test Suite. https://github.com/MichaelClerx/cellml-validation -->
<!-- CellML 1.0, 3.4.3.3: A variable can have a local component unit -->
<model name="variable_units_component"
       xmlns="http://www.cellml.org/cellml/1.0#">
  <component name="A">
    <units name="oranges">
      <unit units="volt" />
    </units>
    <variable name="a" units="oranges" />
  </component>
</model>
```

**Comment by MauriceHendrix** [comment]
Is this specifically units inside components that are not allowed, or units anywhere not at the root level?
Is this also the case for other elements (components, groups, connection)?

**Comment by MichaelClerx** [comment]
CellML 1.0 and 1.1 allow them inside <model> or <component> elements. If they appear anywhere else the pre-validation we run with RelaxNG will produce an error.
But in cellmlmanip we're not supporting the (valid) placement of units in components, so we need an extra check + error msg

**Comment by MauriceHendrix** [comment]
This is already implemented and tested in `test_parser.py`, `def test_component_units_unsupported(self):`

However if you run that example you give you get `KeyError: 'Unknown unit <oranges>.'` just because components are processed after units.
