### ISSUE TITLE
Question regarding test_simple_odes.cellml and state units conversion in particular

### ISSUE THREAD

**Issue by agarny** [ModellingWebLab/cellmlmanip#36]
Hi, I am currently having a look at your [test_simple_odes.cellml](https://github.com/ModellingWebLab/cellmlmanip/blob/develop/tests/cellml_files/test_simple_odes.cellml) file and I was wondering whether:
 - [`0.001`](https://github.com/ModellingWebLab/cellmlmanip/blob/develop/tests/cellml_files/test_simple_odes.cellml#L453) shouldn't be in `volt_per_ms` rather than in `mV_per_s`; and
 - [`1000`](https://github.com/ModellingWebLab/cellmlmanip/blob/develop/tests/cellml_files/test_simple_odes.cellml#L503) shouldn't be in `uV_per_ms` rather than in `mV_per_usec`?

(Same for [`sv1_rate`](https://github.com/ModellingWebLab/cellmlmanip/blob/develop/tests/cellml_files/test_simple_odes.cellml#L462) and [`sv1_rate`](https://github.com/ModellingWebLab/cellmlmanip/blob/develop/tests/cellml_files/test_simple_odes.cellml#L512).)

Indeed, the only conversion of units that CellML requires is at the mapping level. So, normally, no conversion should be done for those equations?...

**Comment by jonc125** [comment]
Good catch, I think this was a copy&paste error because I did the time_units_conversion versions first!

**Comment by jonc125** [comment]
They become useful for testing the protocol interface, where the protocol has V in mV and time in ms. It ensures the units conversion at that interface handles derivatives correctly whether they occur on the LHS or RHS of equations.

**Comment by agarny** [comment]
> They become useful for testing the protocol interface, where the protocol has V in mV and time in ms. It ensures the units conversion at that interface handles derivatives correctly whether they occur on the LHS or RHS of equations.

Oh, I see now. Thanks for the clarification @jonc125.
