### ISSUE TITLE
Add RDF processing

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/cellmlmanip#39]
For looking up variables by annotation we need to process the RDF in a model as a graph, in the same way as the [cellml_metadata.py](https://chaste.cs.ox.ac.uk/trac/browser/chaste/trunk/python/pycml/cellml_metadata.py) file in pycml.

Other useful bits of pycml code are the methods `get_variable_by_oxmeta_name` and `get_variables_by_ontology_term` in [pycml.py](https://chaste.cs.ox.ac.uk/trac/browser/chaste/trunk/python/pycml/pycml.py#L440), which use the RDF methods to do variable lookups, and are themselves used by the model manipulation code as the high-level interface. (Though we should probably have `get_variable_by_ontology_term` instead of `get_variable_by_oxmeta_name`, and pass it a full URI not local name.)

- [ ] Probably we should add a `metadata.py` file to cellmlmanip containing essentially the same public interface as the pycml metadata file.
    - We don't need to be able to serialise RDF back out
    - It may be better to define a class and have cellmlmanip models contain an instance of this class which provides access just to that model's RDF, rather than having a separate class that has a map of models to graphs.
    - The call to `cellml_model.xml_xpath(u'*/cml:variable[@cmeta:id="%s"]' % var_id)` should instead call the existing get var by cmeta_id method.
    - Some methods may not be needed by Web Lab, only Chaste code gen; only copy stuff needed by `find_variables` in the first instance.
- [ ] We should also copy the .ttl version of the ontology over (require rdflib >= 4 in our dependencies)
    - Eventually we'll want to have a single source of truth for the Web Lab ontologies, but for now each project that needs it can have its own copy.
    - This is only needed for the `transitive_subjects` method which is part of the advanced interface used for arbitrary vector outputs
- [ ] We'll need some tests
    - Have a test model with some basic metadata, and check that each of our public methods give the expected results. We might be able to reuse an existing test model for this.
    - `test_simple_odes.cellml` has the following annotations (I've used the `oxmeta` prefix purely for brevity, and the `cmeta:id` on the right):
        - `oxmeta:time` on `time`
        - `oxmeta:sodium_reversal_potential` on `sv11`
        -  many others like this
        - `urn:test-ns#parameter_a1` on `a1`
    - So we could test (in order of implementing):
        - `get_variable_by_ontology_term(oxmeta + 'time')` gets you `time`
        - `get_variable_by_ontology_term(oxmeta + 'membrane_stimulus_current')` throws as not found
        - `get_variables_by_ontology_term(oxmeta + 'ExtracellularConcentration')` gets you `[]`
        - `get_variables_by_ontology_term(oxmeta + 'ExtracellularConcentration', transitive=True)` gets you `[y1]`
        - `get_variables_by_ontology_term(oxmeta + 'Concentration', transitive=True)` gets you `[x1, y1]`
    - [x] I'll write another CellML with error cases
        - get_variable_by_ontology_term(oxmeta + 'time')` gives 2 variables not 1
        - get_variable_by_ontology_term(oxmeta + 'membrane_potential')` cmeta:id doesn't exist
        - get_variable_by_ontology_term(oxmeta + 'membrane_fast_sodium_current')` cmeta:id isn't a variable
        - get_variable_by_ontology_term(oxmeta + 'membrane_persistent_sodium_current')` annotates something outside the model file
- [ ] Possibly the magic handling of `oxmeta:state_variable` should be in `cellmlmanip` rather than `weblab_cg`?

**Comment by MichaelClerx** [comment]
Why in a separate module? Should it not just be part of the Model class?

**Comment by jonc125** [comment]
I suppose it could be. I was just thinking a separate class makes things cleaner because it's a logically separate bit of functionality, that just gets used by the `Model` (composition pattern). Which makes it easier to see all the RDF-related functionality together.

**Comment by jonc125** [comment]
I've written a CellML file with 4 annotation error cases. Do you have a branch for this I can stick it in @MichaelClerx ? Or shall I send it to you on Slack?

**Comment by MichaelClerx** [comment]
Thanks! I've just created a branch `metadata-lookups` for this

**Comment by MichaelClerx** [comment]
@jonc125 I'm going to do this one in phases, adding in methods when I need them (starting with getting a single variable). Is that alright?

**Comment by jonc125** [comment]
Done in various other places already.
