### ISSUE TITLE
Don't be too nice about unit conversion

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#46]
In CellML, unit conversion should only happen when connections between components are made.

For example:
```
x.y = 1 cm
y.z = x.y in m
```
here a good cellml reader should know to add in a multiplication factor

In cases like this:
```
x.y = 1 cm
x.z = x.y in m
```
a good cellml reader should fail. (The spec also seems to say that a bad cellml reader in this case should continue without conversion)

similarly
```
x = 1 m + 10 cm
```
should fail

**Comment by jonc125** [comment]
Part of the problem is that the CellML 1 spec is unclear what should happen here - it says software *may* convert but doesn't *have* to...

**Comment by MichaelClerx** [comment]
Yeah. That bit doesn't make sense :-)
I'm pretty certain it only ever discusses unit conversion in the context of making connections though, so we should make sure we check that, internally, the components and equations are consistent without requiring conversion
