### ISSUE TITLE
Rewrite transpiler to use etree instead of dom

### ISSUE THREAD

**Issue by tamuri** [ModellingWebLab/cellmlmanip#51]
Investigate why the mathml2sympy transpiler doesn't like a reference to the MathML DOM element. Currently passing string representation of the MathML.

See `_add_maths` in `parser.Parser`

**Comment by MichaelClerx** [comment]
Looks like this was fixed @tamuri ?

**Comment by tamuri** [comment]
No, still as it was: https://github.com/ModellingWebLab/cellmlmanip/blob/a650cd3763e35b0a3490b7d762aac48267114c26/cellmlmanip/parser.py#L239

**Comment by MichaelClerx** [comment]
OK, the main parsing is done with `etree`, while the transpiler uses the DOM, that's why we need XML conversion in between.

Could replace this ticket with "rewrite transpiler to use etree" then, @jonc125 ?

**Comment by jonc125** [comment]
Makes sense!
