### ISSUE TITLE
Infinite loops in unit parsing

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#52]
The following files cause an infinite loop when parsing:

- https://github.com/MichaelClerx/cellml-validation/blob/master/models_1_0/invalid/5.4.2.2.unit_cycle_1.cellml
- https://github.com/MichaelClerx/cellml-validation/blob/master/models_1_0/invalid/5.4.2.2.unit_cycle_2.cellml
- https://github.com/MichaelClerx/cellml-validation/blob/master/models_1_0/invalid/5.4.2.2.unit_cycle_3.cellml
- https://github.com/MichaelClerx/cellml-validation/blob/master/models_1_0/invalid/5.4.2.2.unit_units_invalid.cellml

**Comment by tamuri** [comment]
fixed

**Comment by tamuri** [comment]
...but not merged
