### ISSUE TITLE
Delete `master` branch?

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#60]
For now, this is develop only. So maybe delete `master` until we have a first release @jonc125 ?

**Comment by jonc125** [comment]
Could do. Although I think because of the GitHub settings everything should default to using `develop` anyway, and we can merge to `master` for the first release, rather than creating it then?

**Comment by MichaelClerx** [comment]
I was thinking more along the lines of not confusing newcomers :-)

**Comment by jonc125** [comment]
Where do newcomers get confused currently? They get shown the develop branch by default on GitHub, and when they clone, I believe?

**Comment by MichaelClerx** [comment]
OK, let's just leave it then!
