### ISSUE TITLE
Import maths from a CellML file

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/cellmlmanip#7]
Not trying to do any CellML validation here (that's down to libCellML) just getting the maths from components and connecting up variables.

- [ ] Extract maths from each component and convert separately
- [ ] Ensure that variables in different components with the same name don't accidentally get equated by Sympy's symbol cache
- [ ] Process connections and add `sympy.Eq` accordingly
- [ ] Import units definitions (requires #8)

**Comment by tamuri** [comment]
See https://github.com/ModellingWebLab/project_issues/issues/34#issuecomment-359449404
