### ISSUE TITLE
model.get_symbol_by_ontology_term not working in some cases , caused by get_symbol_by_cmeta_id not working

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/cellmlmanip#71]
with `OXMETA = "https://chaste.comlab.ox.ac.uk/cellml/ns/oxford-metadata"`
I do: `model.get_symbol_by_ontology_term(OXMETA, "test")`
and get: `KeyError('No variable with cmeta id "membrane_voltage2" found.')`

key extract from cellml
```python
      <variable name="pqr" units="uF_per_mm2" initial_value="0.01" cmeta:id="membrane_voltage2">
         <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:bqbiol="http://biomodels.net/biology-qualifiers/">
            <rdf:Description rdf:about="#membrane_voltage2">
               <bqbiol:is rdf:resource="https://chaste.comlab.ox.ac.uk/cellml/ns/oxford-metadata#test"/>
            </rdf:Description>
         </rdf:RDF>
      </variable>	  
```
[beeler_reuter_model_1977-Copy.cellml.txt](https://github.com/ModellingWebLab/cellmlmanip/files/3554443/beeler_reuter_model_1977-Copy.cellml.txt)

**Comment by MichaelClerx** [comment]
Can you put the rest of the file somewhere?

**Comment by jonc125** [comment]
In particular, do you have a variable with a `cmeta:id="membrane_voltage2"` attribute? If not, that's the (expected) error you'll get. The RDF annotation needs to have something to point at.

**Comment by MauriceHendrix** [comment]
> Can you put the rest of the file somewhere?

attached

**Comment by MauriceHendrix** [comment]
> In particular, do you have a variable with a `cmeta:id="membrane_voltage2"` attribute? If not, that's the (expected) error you'll get. The RDF annotation needs to have something to point at.

sorry I mixed up the error message in my original post now double checked and corrected

**Comment by jonc125** [comment]
Hmm, I can't see anything obviously wrong with the model as attached. You're sure that's the version you're using to get that error?

**Comment by tamuri** [comment]
Sorry, AFK, but is the variable used in an equation?

**Comment by MauriceHendrix** [comment]
> Sorry, AFK, but is the variable used in an equation?

No but even if I add the annotation to one that is used in an equation I get the same error:

`model.get_symbol_by_ontology_term(OXMETA, "test")`
`get: KeyError('No variable with cmeta id "membrane_voltage2" found.')`

for:

```python
   <component name="environment">
      <variable name="time" units="ms" public_interface="out"/>
   </component>
   <component name="membrane">
      <variable name="V" units="mV" initial_value="-84.624" public_interface="out" cmeta:id="membrane_voltage">
         <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:bqbiol="http://biomodels.net/biology-qualifiers/">
            <rdf:Description rdf:about="#membrane_voltage">
               <bqbiol:is rdf:resource="https://chaste.comlab.ox.ac.uk/cellml/ns/oxford-metadata#membrane_voltage"/>
            </rdf:Description>
         </rdf:RDF>
      </variable>
      <variable name="pqr" units="uF_per_mm2" initial_value="0.01"/>  
      <variable name="C" units="uF_per_mm2" initial_value="0.01"/>
      <variable name="time" units="ms" public_interface="in"/>
      <variable name="i_Na" units="uA_per_mm2" public_interface="in" meta:id="membrane_voltage2">
         <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:bqbiol="http://biomodels.net/biology-qualifiers/">
            <rdf:Description rdf:about="#membrane_voltage2">
               <bqbiol:is rdf:resource="https://chaste.comlab.ox.ac.uk/cellml/ns/oxford-metadata#test"/>
            </rdf:Description>
         </rdf:RDF>
      </variable>		  
      <variable name="i_s" units="uA_per_mm2" public_interface="in"/>
      <variable name="i_x1" units="uA_per_mm2" public_interface="in"/>
      <variable name="i_K1" units="uA_per_mm2" public_interface="in"/>
      <variable name="Istim" units="uA_per_mm2" public_interface="in"/>
      <math xmlns="http://www.w3.org/1998/Math/MathML">
         <apply>
            <eq/>
            <apply>
               <diff/>
               <bvar>
                  <ci>time</ci>
               </bvar>
               <ci>V</ci>
            </apply>
            <apply>
               <divide/>
                  <apply>
                     <minus/>
                     <ci>Istim</ci>
                     <apply>
                        <plus/>
                        <ci>i_Na</ci>
                        <ci>i_s</ci>
                        <ci>i_x1</ci>
                        <ci>i_K1</ci>
                     </apply>
                  </apply>
               <ci>C</ci>
            </apply>
         </apply>
      </math>
   </component>
```

**Comment by jonc125** [comment]
Two issues there:
* You have a typo `meta:id` not `cmeta:id`
* You can't annotate a variable with an 'in' interface, you have to annotate the (ultimate) source variable

**Comment by MauriceHendrix** [comment]
hhm that's confusing I guess method comments need to warn users of that

**Comment by jonc125** [comment]
The 'in' interface thing is more a CellML rule than our software. We possibly should give an error message for it as part of stricter validation (e.g. #45).

The 'used in an equation' part is just that cellmlmanip focuses on maths so ignores bits of the model that don't appear in equations. Possibly we should make an exception for variables and always create symbols for them, to avoid confusion in this kind of case?
