### ISSUE TITLE
Getting units and other meta data from dummy objects

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/cellmlmanip#72]
we would like to not have cellmlmanip replace dummies with numbers, as that creates errors in summarys_units. However we need to recognise numbers for printing.

The plan is to use a dedicated subclass see  def add_number in model.py

**Comment by MichaelClerx** [comment]
jonathan  5 days ago
> I guess this is really an API design question then. Would the code generation like to call two methods (get_equation_graph then do substitutions - useful if these operations are sometimes separated) or a single method (get_substituted_equation_graph?) which calls the two separate methods behind the scenes.
> Sounds like we should start with the two methods (and update the failing test to call both) and add the helper method if it seems useful?

Maurice  5 days ago
> with the 2 methods it is definitely more transparent what is happening
> I can have a stab at it in a branch
> one of the issues I have is that I'm doing more processing after I've done some printing. I could change order or instead of doing stubstitutions in the model I can do it for a specific equation (that I'm trying to print)
> ```def substitute_number_dummies(self, equation: sympy.Eq) -> sympy.Eq:```
> does that seems sensible?

jonathan  5 days ago
> it sounds like for this use case the equations in the Model shouldn't change, but you should be able to get a substituted version of a set/graph of equations?

Maurice  5 days ago
> yes that's what that method would do
> but just for an equation
> I can of course do it for the whole graph but that isn't too useful for me as I'm never using this directly instead using various other methods that work on the graph
> I'll try and check with Michael what he thinks

jonathan  5 days ago
> I'd guess having a method to do it for one equation would still be useful in the case that you want to do it for a whole graph, as you can just call the method repeatedly!

tamuri  5 days ago
> What do you mean by printing? You mean print the equation to screen?

Maurice  5 days ago
> no to the model generation
> slight hange of plan I discussed with Michael and we'll look into whether we can make dummies that are numbers a subclass so we can easily recognise them.
> or is there a way to find out if a dummy is actualy a number?
> found it I think

tamuri  5 days ago
> Have a look at ExpressionWithUnitPrinter in cellmlmanip.units
> That takes the model dummy_metadata and can print dummified equations
> 
>    p = ExpressionWithUnitPrinter(model.dummy_metadata)
>    p.doprint(equations_with_dummies)
> 
> We did discuss subclassing Symbol/Dummy but decided against it so we wouldn't mess with Sympy internals (there's a lot of magic happening in there)

Maurice  5 days ago
> nope that's not helping
> once I disable substitutions in get_equation_graph that method gets me something like
>
>    '1000.000000[millisecond]' (edited)
>
> what I could do in our sumbol_name function:
> 
>     # Symbol naming function
>     def symbol_name(symbol, prefix = 
>                      "chaste_interface__"):
>         try:
>             return 'var_' + prefix + unames[symbol]
>         except:
>             return symbol.name 
> 
> @michael Not very elegant what do you think? (edited)

tamuri  4 days ago
> I know it doesn't produce what you need. I meant as an example of how you can use dummy_metadata to distinguish between symbols and numbers.

Maurice  4 days ago
> It still doesn't give you a way of distinguishing though? It just prints it.

jonathan  4 days ago
> if self.symbols[expr].is_number:
> Used in def _print_Dummy(self, expr):
> where self.symbols is set from  model.dummy_metadata

Maurice  4 days ago
> hhmm why do we need to know about dummymetadata from outside the model?

jonathan  4 days ago
> So you can tell what the dummy symbols represent
jonathan  4 days ago
> Some of this could migrate into helper methods on Model perhaps
jonathan  4 days ago
> (though then the printer would need a reference to the model instance...)

michael  4 days ago
> >
> >   hhmm why do we need to know about dummymetadata from outside the model?
> >
> I agree with @maurice here! A user of cellmlmanip shouldn't have to know about dummy's, dummy meta data, or the dummy meta data store

jonathan  4 days ago
> Except if you care about units (which you should!) then unfortunately you do as just using Sympy's units model didn't work :disappointed:

michael  4 days ago
> So our API is just sympy and a dict then? That's hardly the right level of abstraction?
> Surely if we wrap around the Dummy object, make sure we don't override the constructor, and add some carefully chosen field/method names we can subclass without ruining Sympy's internals?

jonathan  4 days ago
> IIRC the tricky bit is getting Sympy to create your new objects if/when it manipulates the equations

michael  4 days ago
> Hmmmm! OK I can see that. So then should we have an old C-style API where you do e.g.
> 
>    model.get_unit(dummy)
> 
> rather than
> 
>    dummy.get_unit()
> 
> ?

jonathan  4 days ago
> I think so, yes, so the Model holds all the 'extra' CellML info and the Sympy equations are just maths

jonathan  4 days ago
> Feel free to make suggestions (including try things out in PRs!) and we'll see what works best :slightly_smiling_face:

tamuri  4 days ago
> There's some discussion in the Sympy issues/group forum about subclassing. The main author (Meurer) said that subclassing things in Sympy can create lots of problems. That was at the start of cellmlmanip, so maybe the situation has improved (the "Make Symbol better for subclasses" issue is still open) (edited)

**Comment by MichaelClerx** [comment]
maurice
> Hi Michael. I've been having a look at this this morning but haven't been able to come up with a great solution so far, feel free to have a go yourself.

> I tried removing the replace in get_equation_graph. This kinda works. You do have to do some extra work before printing, but also it breaks one of the tests for cellmlmanip: test_evaluation at the very end: assert float(actual) == pytest.approx(expected) fails as actual is not seen as a float.

> This isn't great as actual is just a formula with only numbers, so it indicates that without the replace you would have to do extra work would be able to use the sympy expressions

**Comment by MichaelClerx** [comment]
I'm confused about how all of this is supposed to work. @tamuri maybe you could help clarify some things?

So... 
- none of the unit information lives inside the Sympy objects
- all constants(?) and variables are dummies, so that Sympy won't simplify them
- we can traverse a sympy expression, and each time we see a dummy look up its units
- this allows us to check if a variable's RHS has the unit the variable should have (the unit of its LHS)
- to evaluate expressions, we can traverse them and replace number dummies by numbers

Is that right so far?

But what happens when we start doing fun stuff like taking derivatives? 
- Presumably this will give massive equations unless we allow sympy to simplify?
    - Are dummies treated as potential variables? Because that would lead to very complex equations if you do symbolic derivation
- Does this mean that, after any kind of operation, we lose all information about units etc?

**Comment by tamuri** [comment]
> - none of the unit information lives inside the Sympy objects
> - all constants(?) and variables are dummies, so that Sympy won't simplify them
> - we can traverse a sympy expression, and each time we see a dummy look up its units
> - this allows us to check if a variable's RHS has the unit the variable should have (the unit of its LHS)
> - to evaluate expressions, we can traverse them and replace number dummies by numbers

That's all correct. Re. constants: all numbers and variables in the math are represented by dummies. 

> But what happens when we start doing fun stuff like taking derivatives? 
> - Presumably this will give massive equations unless we allow sympy to simplify?

As you say above, the dummies stop Sympy from automatically simplifying the equations. `.replace` of Dummy with a Symbol will let Sympy simplify the equation.

> - Are dummies treated as potential variables? Because that would lead to very complex equations if you do symbolic derivation
> - Does this mean that, after any kind of operation, we lose all information about units etc?

Probably depends on the kind of operation. With current implementation, we have to control/manage the operations to make sure unit information is preserved. The only manipulation currently implemented is `model.connect_variables` which checks the units and adds a new equation with a scaling factor (which has units).

**Comment by MichaelClerx** [comment]
Maybe we should make it a priority to try and get some model derivatives. I think the way that's done is just following the rules for derivatives of every operator, which means you need quite a bit of simplification afterwards to make it readable again. But then maybe sympy is clever to do that even with all the dummies in place? (Just not things like `1 * 2 = 2`, which would stay `dummy(1) * dummy(2)` ?)
Sounds like the kind of thing we need to find out to see if this strategy will hold

**Comment by MauriceHendrix** [comment]
> > * all constants(?) and variables are dummies, so that Sympy won't simplify them

Why exactly is this a problem actually?

**Comment by tamuri** [comment]
> Why exactly is this a problem actually, remind me again?

We use dummies keep a handle on the units of within the expression, and we get to control exactly when simplification happens (by, e.g., replacing dummies by things Sympy can simplify). Simplification is not a problem per se.

**Comment by MichaelClerx** [comment]
Well, if we have an equation `I = 5 * g * x(t) * (V - E)` or something like that, then I'm happy enough. But if start getting things like `5 * 2 / 1 * 7 * x(t) ...` etc., where even the 1 won't go away because it's a dummy, then I'm not sure we're doing it right
Or even a `... + 0 * ... + 1 / 1 * ...` where both 1s are in the same unit, but different dummies
In that case I'd want a unit-aware simplification

**Comment by MichaelClerx** [comment]
(and I think it's quite likely we'll get equations like the 2nd example I gave above once we start taking symbolic derivatives of things)

**Comment by jonc125** [comment]
So, there are operations for which you need units and others for which you don't. You need the units initially to check the model and implement connections. And you need them for some protocol/Chaste features (ensuring inputs & outputs are in correct units, transforming derivatives if converting time, etc). But I think there are relatively few operations that need to evaluate the units of an expression, and we can probably do those early then replace all constant dummies, before things like computing Jacobians. Keeping dummies for variable symbols until later is less likely to impact simplification, and those are all that later-stage transformations are likely to need.
