### ISSUE TITLE
Move .coveragerc out of cellmlmanip module

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#76]
Is part of the infrastructure, not of the cellmlmanip module, so should live in project root.

While making this change, perhaps travis config can be simplified to just:

```
pytest --cov
```

because the `.coveragerc` file is now in the default location (so no need to be explicit), and the remaining settings are already set in the `setup.cfg`, so current config is defining them twice / redefining

**Comment by jonc125** [comment]
Fixed by #105.
