### ISSUE TITLE
Add validation using RNG

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#79]
It would be ideal if models were validated when read in by cellmlmanip.

Also, need a flag to allow this to be turned off if we dont want it.

**Comment by MichaelClerx** [comment]
See example here: https://github.com/MichaelClerx/cellml-validation/blob/master/check/_validation.py#L54-L81

And see also discussion at #45

**Comment by MichaelClerx** [comment]
And for the MathML part specifically, see #10

**Comment by MichaelClerx** [comment]
Done in #181
