### ISSUE TITLE
Parsing of simple mathematical models - from Model Manipulation

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#80]
Remaining items on this section of #21 

* [x] See [existing pure MathML tests](https://github.com/ModellingWebLab/weblab-fc/blob/master/test/protocols/test_mathml_evaluation.txt) - stick these in components
* [x] With single connection
* [x] Include a purely algebraic system as well as ODEs
* [x] Ensure variables have units and annotations associated
    * [x] Single 'bqbiol:is' annotation
    * [x] Multiple 'bqbiol:isVersionOf' annotations
    * [x] Be able to access the annotations of a variable (subject = cmeta:id, property, object)
* [x] Ensure numbers have units associated (just to be able to support getting the units for an equation, below)
* [x] Units conversions at connections - add new equations to model
* [x] Ensure encapsulation is treated correctly
    * [x] Two 'global' components can connect
    * [x] A parent and child can connect in both directions
    * [x] Accessing a hidden component gives error

@jonc125 will need you to expand on what this means. I'm assuming you mean create CellML models with the MathML inside.

**Comment by jonc125** [comment]
Indeed, that was the idea. Up to you how much of this you think we need, or whether we can just reuse @MichaelClerx 's test cases. To some degree basic math support (at least for model manip & code gen) will be tested just by running that protocol once everything connects up!

**Comment by MichaelClerx** [comment]
Probably better to have some unit tests as well though, no?

**Comment by jonc125** [comment]
Indeed, it's just a question of how much to prioritise now. Enough that you're confident it's doing what's needed...
