### ISSUE TITLE
Analysing systems of equations - from Model manipulation

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#81]
Remaining items from this section of #21 

* [x] Checking for over/under-determined cases
* [x] Identifying free/state/computed variables
* [x] ~Can we do this ignoring the directionality on interfaces? (Makes future CellML 2 support easier.)~
* [x] Handle initial values nicely
    * [x] Where these are actually constants, make them look like a simple assignment
    * [x] Where they are really initial values for state vars, store them separately
        * In CellML 2 these could be computed by an equation, but we don't need that for now
* [x] Figure out the units for an equation (or part of an equation, e.g. the RHS of an assignment) cf #8

**Comment by jonc125** [comment]
The 'ignoring directionality' somewhat refers generically to all model analysis. At present we're assuming equations are always assignments to a single variable or derivative. This isn't necessarily the case, particularly in CellML 2, but is for all models we (currently) care about. So it's more a case of don't assume it if it's easy not too, but not worth putting lots of effort into being generic yet!

**Comment by skeating** [comment]
Is there a priority need for any of the above as present ?

**Comment by MichaelClerx** [comment]
The initial value bit. (See also #135 )

**Comment by MichaelClerx** [comment]
I've crossed out the bit about CellML 2 if that's ok @jonc125 . More of a stretch goal now?

**Comment by jonc125** [comment]
Regarding over/under-determined, this basically falls out from categorising variables: if your equations imply that a variable has two different types, or two defining equations, or no definition at all, or an unknown type.
