### ISSUE TITLE
Parsing of realsitic models - from Model manipulation

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#82]
Remaining items from this section of #21 

* [x] Check we can parse all the models in Chaste's CellML project
* [ ] We possibly don't want to check all the equations manually, but doing a few cases might be wise

@jonc125 Would this be solved by creating CellML models with various MathML in eg #80

**Comment by jonc125** [comment]
No, this is different from testing just basic MathML, it's testing some actual cardiac models. Again this gets implicitly tested by running full protocols on them, so it's just a question of degree as to how much we need. Perhaps worth checking at least hodgkin-huxley!?

**Comment by MichaelClerx** [comment]
One way to check is to evaluate the RHS and then compare the calculated derivatives with some reference tool. I think @tamuri did this at some point

**Comment by tamuri** [comment]
> I think @tamuri did this at some point

I did, but looks like its been removed.

**Comment by MichaelClerx** [comment]
Still here a few weeks ago: https://github.com/ModellingWebLab/cellmlmanip/blob/2419d8bf12e896e781a8516597d4d301e0f3fb70/tests/test_hodgkin.py#L139

**Comment by MichaelClerx** [comment]
Hmmm, yup disappeared in #116 .

Wonder if we should bring it back in some form, @jonc125 ?

**Comment by skeating** [comment]
So test_hodgkin disappeared when I removed all test_specific_model files and incorporated the tests in test_model_functions; since we had talked about not having test files named after specific models. I didn't change test coverage when I did this; so clearly the functionality tested here is tested elsewhere but I could see the point of having a test_evaluation file that included the above test for HH and then possibly similar tests for other models if we get round to that.

**Comment by jonc125** [comment]
I wouldn't worry about adding other models, but bringing that specific test for HH back is probably worthwhile (especially as it's easy to do!).

**Comment by MauriceHendrix** [comment]
> I wouldn't worry about adding other models, but bringing that specific test for HH back is probably worthwhile (especially as it's easy to do!). Then we can close this issue.

I think pretty much all "other models" will be implicitly tested because I'm testing their chaste codegen. If they don't parse with cellmlmanip we'll find out soon enough!

**Comment by MichaelClerx** [comment]
> So test_hodgkin disappeared when I removed all test_specific_model files and incorporated the tests in test_model_functions; since we had talked about not having test files named after specific models. I didn't change test coverage when I did this; so clearly the functionality tested here is tested elsewhere 

That makes sense!
Regarding coverage: We've talked about this a lot in PINTS, where we now have an informal rule to try and add value-based tests for every method. I.E. tests that actually check the output is correct.
I've heard about structured ways of doing this but they all sound like a lot of work / extra software

**Comment by jonc125** [comment]
Do you mean tools like [hypothesis](https://hypothesis.readthedocs.io/en/latest/)? Not directly, but I've seen them used.
