### ISSUE TITLE
Is there a way to get the equations form celll with lower precision?

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/cellmlmanip#86]
Is there a way to get the equations form celll with lower precision? reason I'm asking is the following example. The 1st pycml 2nd is (chaste formatted) cellml output:

```var_time_dependent_outward_current_x1_gate__alpha_x1 = (0.00050000000000000001 * exp((var_time_dependent_outward_current_x1_gate__V + 50.0) / 12.1)) / (1.0 + exp((var_time_dependent_outward_current_x1_gate__V + 50.0) / 17.5))```

```var_time_dependent_outward_current_x1_gate__alpha_x1 = 0.031158410986342627 * exp(0.08264462809917356 * var_time_dependent_outward_current_x1_gate__V) / (1.0 + 17.41170806332765 * exp(0.05714285714285714 * var_time_dependent_outward_current_x1_gate__V))```

if I read in the 1st one in sympy I get the following.
```var_time_dependent_outward_current_x1_gate__alpha_x1 = 0.031158410986342628 * exp(0.0826446280991736 * var_time_dependent_outward_current_x1_gate__V) / (17.4117080633277 * exp(0.0571428571428571 * var_time_dependent_outward_current_x1_gate__V) + 1.0)```

If I could reduce precision slightly I could detect those as the same, but as it stand I don't have a way of determining what cellml gives as correct.

**Comment by mirams** [comment]
So cellmlmanip simplifies / multiplies out when pycml doesn't (leaves it to compiler)?

I think we can probably compare numbers to 10 decimal places or something, or perhaps better work out exactly where rounding errors should occur based on known floating point arithmetic limits?

**Comment by MauriceHendrix** [comment]
I think from what I'm reading it's a setting you can change when reading in a float (default 15 digits it says) but when I already have an expression I'm not sure there is a built in way? I can't seem to find it.

**Comment by jonc125** [comment]
Pycml will write out floats with enough digits to guarantee they get represented as the same IEEE double when read back in.

Another issue is that sympy always represents equations in canonical form, which may eg reorder terms multiplied together.

So perhaps for a fully automated comparison we'd need to parse the C++ output into sympy and compare that?

--
Written on a smartphone; please excuse brevity!

________________________________

**Comment by MauriceHendrix** [comment]
> out floats with enough digits to guarantee they get represented as the same IEEE double when read back in. Another issue is that sympy always represents equations in canonical form, which may eg reorder terms multiplied together.

That's exactly what I was doing but it doesn't work in the example as sympy will (correctly) tell me they are slightly different and any automated test would fail. It's fine at coping with the reordering but not at comping with this difference in precision.

**Comment by jonc125** [comment]
Check output_number in pycml to see what precision it uses?

**Comment by jonc125** [comment]
Can you get sympy to output the same? Or read the numbers in and compare as doubles ( which should match)?

--
Written on a smartphone; please excuse brevity!

________________________________

**Comment by MauriceHendrix** [comment]
That is the question indeed. Can we tell sympy what precision to use?
I looked into it but I can't find anything that works. For example:
```
>>> x1 = sp.sympify('(0.00050000000000000001 * exp((var_time_dependent_outward_current_x1_gate__V + 50.0) / 12.1)) / (1.0 + exp((var_time_dependent_outward_current_x1_gate__V + 50.0) / 17.5))')
>>> x1.evalf(3)
0.0312*exp(0.0826446280991736*var_time_dependent_outward_current_x1_gate__V)/(17.4*exp(0.0571428571428571*var_time_dependent_outward_current_x1_gate__V) + 1.0)

```

**Comment by tamuri** [comment]
The second argument to `sympy.Float` allows you to specify precision. You could perhaps replace the floats in symbol's metadummy entry with one of higher precision or change the `<cn>` code in mathml2sympy code

**Comment by tamuri** [comment]
sympy uses mpmath (I think it's the same team?) under the covers, [this documentation](http://mpmath.org/doc/current/technical.html) might be helpful.

**Comment by MichaelClerx** [comment]
Is this an issue with our approach of letting sympy modify the equations?

It seems in the example at the top that there must have been some tiny discrepancy between the way floats were read or stored, and then that gets amplified when sympy does a bunch of floating point operations on the numbers.

We could use a higher precision float like @tamuri is suggesting, and that might hide this issue? Might make evaluation slow though, but that's probably fine?

It sounds good to me, but wondering if there's some way this can come back round to bite us in the future somehow :D

**Comment by MauriceHendrix** [comment]
> sympy uses mpmath (I think it's the same team?) under the covers, [this documentation](http://mpmath.org/doc/current/technical.html) might be helpful.

I tried that but the precision only affects calculations it's completely ignored when reading in an expression as a string with sympify.

**Comment by MauriceHendrix** [comment]
> Is this an issue with our approach of letting sympy modify the equations?
> 
> It seems in the example at the top that there must have been some tiny discrepancy between the way floats were read or stored, and then that gets amplified when sympy does a bunch of floating point operations on the numbers.
> 
> We could use a higher precision float like @tamuri is suggesting, and that might hide this issue? Might make evaluation slow though, but that's probably fine?
> 
> It sounds good to me, but wondering if there's some way this can come back round to bite us in the future somehow :D

I would need lower precision not higher!

**Comment by MichaelClerx** [comment]
Can we make `sympify` use `evaluate=False` to skip the simplification until we explicitly ask it to?

**Comment by MauriceHendrix** [comment]
> We could use a higher precision float like @tamuri is suggesting, and that might hide this issue? Might make evaluation slow though, but that's probably fine?

Actually I really DO need lower precision to match what I get from pycml. I can't get higher precision on that as it's read in from a text file (well cpp class but same thing). I just want this

**Comment by MichaelClerx** [comment]
You can't do the test. For whatever reason the numbers aren't read in 100% the same, and you say you have no control over that. After that, some unknown number of floating point operations happen, each introducing some unknown error that depends on the floats involved. So we don't know what error to expect because we don't know the exact operations that occurred. So you could do a lower precision test, but how much lower? How can we tell that it's justified?

If, instead, you use really high precision why sympy does its magic, then you could throw away precision afterwards (it wasn't in that precision in the file anyway, so that's fine). But now all the floating point errors accumulated at a tiny scale that disappears when you go back to normal doubles?

**Comment by MichaelClerx** [comment]
Then again, you could just use static "expected result" files, test against those. Modify them if you're sure what you're doing is right?

**Comment by MauriceHendrix** [comment]
> Then again, you could just use static "expected result" files, test against those. Modify them if you're sure what you're doing is right?

Yeah but that's the thing I am not and the test against pycml output is to verify that it is right.

**Comment by MichaelClerx** [comment]
But cases like you show above, you know that they're fine, right? So just modify the expected outcome file for each of them

We don't need a tool that does exactly what pycml does. Pycml already does that

**Comment by jonc125** [comment]
Do the errors you're seeing happen at the limits of IEEE double precision (in which case, we're justified in ignoring them)? Or is there a difference at a more significant decimal place? What's the highest power of 10 that's wrong?

**Comment by MauriceHendrix** [comment]
From what I read an IEEE double has 15 decimal places. Errors seem to at 15th 16th or 18th digit.

**Comment by jonc125** [comment]
From https://www.exploringbinary.com/number-of-digits-required-for-round-trip-conversions/ - if you output 17 digits then read in again, you're guaranteed to end up with the same `double` you started with. However, given a decimal starting number, if you read in to `double` then print you're only guaranteed to get the first 15 digits the same. So we only need to check against the first 15 if we're comparing as decimal strings.

**Comment by MauriceHendrix** [comment]
> From https://www.exploringbinary.com/number-of-digits-required-for-round-trip-conversions/ - if you output 17 digits then read in again, you're guaranteed to end up with the same `double` you started with. However, given a decimal starting number, if you read in to `double` then print you're only guaranteed to get the first 15 digits the same. So we only need to check against the first 15 if we're comparing as decimal strings.

first 15 or round at 15?
e.g. 17.41170806332765 vs 17.4117080633277

**Comment by jonc125** [comment]
Round at 15 I think

**Comment by skeating** [comment]
I agree with precision but also note that we need to revisit letting sympy 'work things out' as I have a model it read in where it happily added 1 second and 2 metres (both declare as cn elements  in mathml) and just returned 3 as part of the equation.

**Comment by MauriceHendrix** [comment]
> I agree with precision but also note that we need to revisit letting sympy 'work things out' as I have a model it read in where it happily added 1 second and 2 metres (both declare as cn elements in mathml) and just returned 3 as part of the equation.

whoopsie

**Comment by jonc125** [comment]
I think that's why Asif kept all numbers as `Dummy`s until units manipulation/conversions done, then replaced with numbers before evaluations.
