### ISSUE TITLE
Pycml linker variables / cllmlmanip - info?

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/cellmlmanip#87]
I'm a little stuck on the derivatives. I'll try to explain the issue I'm having.

Pycml (without partial eval) doesn't write derivative equations directly but uses a linker variable. It also uses one for state symbols. For example (from Decker 2009):

```
const double var_CaMK_active__d_CaMK_trap_d_environment__time = <some expression>
const double var_chaste_interface__CaMK_active__d_CaMK_trap_d_environment__time = var_CaMK_active__d_CaMK_trap_d_environment__time;
const double d_dt_chaste_interface__CaMK_active__CaMK_trap = var_chaste_interface__CaMK_active__d_CaMK_trap_d_environment__time;
```

So far so good, easy enough to replicate **HOWEVER** in beeler_reuter_model_1977 it uses an extra linking variable:

```
const double var_time_dependent_outward_current_x1_gate__d_x1_d_environment__time = <some expression>
const double var_time_dependent_outward_current__time_dependent_outward_current_x1_gate__d_x1_d_environment__time = var_time_dependent_outward_current_x1_gate__d_x1_d_environment__time;
const double var_chaste_interface__time_dependent_outward_current_x1_gate__d_x1_d_environment__time = var_time_dependent_outward_current__time_dependent_outward_current_x1_gate__d_x1_d_environment__time;
const double d_dt_chaste_interface__time_dependent_outward_current_x1_gate__x1 = var_chaste_interface__time_dependent_outward_current_x1_gate__d_x1_d_environment__time;
```

So I'm wondering where the extra variable comes from. The only thing I can come up with is this connection in the cellml? If that's it I can't see a way to get that info from cellmlmanip? Or am I missing something?
```
   <connection>
      <map_components component_1="time_dependent_outward_current" component_2="time_dependent_outward_current_x1_gate"/>
      <map_variables variable_1="x1" variable_2="x1"/>
      <map_variables variable_1="time" variable_2="time"/>
      <map_variables variable_1="V" variable_2="V"/>
   </connection>
```

By the way for info what I get back from cllmlmanip (in chaste formatted form) is just:

`const double d_dt_chaste_interface__CaMK_active__CaMK_trap = <some expression>`
and
`const double d_dt_chaste_interface__time_dependent_outward_current_x1_gate__x1 = <some expression>`

**Comment by jonc125** [comment]
Yeah, the extra equation probably is just for the connection. Without pe pycml won't elide these, but I think cellmlmanip does if there's no units conversion. Which makes more sense, but not so helpful for these tests!

--
Written on a smartphone; please excuse brevity!

________________________________

**Comment by MauriceHendrix** [comment]
In that case I need a way to get connections which I don't think cellmlmanip has?

**Comment by MichaelClerx** [comment]
Tricky! Because we're not going to do anything with connections in cellmlmanip. That was one of the main design ideas.
So this particular model might have to be excluded from tests, or maybe you can hack the test somehow?

**Comment by MauriceHendrix** [comment]
> Tricky! Because we're not going to do anything with connections in cellmlmanip. That was one of the main design ideas.
> So this particular model might have to be excluded from tests, or maybe you can hack the test somehow?

I don't think that's a good idea at all why not just add functionality to get the connections? If they're there in the spec  it would reduce the usefulness of cellmlmanip for the general community if it ignores connections no?

**Comment by MichaelClerx** [comment]
Well you can ask @jonc125 and @tamuri about that, but the idea for cellmlmanip was to

1. Convert CellML into Sympy
2. Discard CellML
3. Manipulate and provide access to the sympy equations

**Comment by MichaelClerx** [comment]
Anyway why on earth would we spend time recreating PyCml funnies like above? If PyCml makes up new variables for no good reason, we're not going to copy that behaviour just to make testing easier

**Comment by MichaelClerx** [comment]
So I'd say don't even replicate the first "linker variable. Just modify the expected output files, and add a comment to them saying you've improved them from what PyCML would do

**Comment by mirams** [comment]
I think this is about being able to do automatic testing just by comparing generated code directly (although simulation is the 'backstop' (!) - we could resort to comparing test results with old and new Chaste simulation files, I'm beginning to think this is sensible even if it isn't as good a test).

With loads of models covering corner cases, and about 5-6 variants (forward Euler, backward Euler, CVODE, w. jacobians, optimised) it would be too much work to manually edit thousands of lines to match PyCML, especially if it involves doing simplifications like above example.

**Comment by mirams** [comment]
With some results of the existing ODE solve I'm worried that variables might stay at zero, and then you wouldn't spot if you missed a time conversion or something (there was a lot of this sort of thing found over a couple of years of PyCML improvement!), which is why comparing generated code is a cleaner idea.

But if we want to go for the simulation backstop, we could fairly easily 'beef up' the existing tests of full action potential simulations by adding a new set of tests that calls each PyCML generated function say ten times with different randomised inputs, records the results of each function call (not doing ODE solves) and then check that you get exactly the same with the new generated code, which might be a bit better as a test that the code does the same thing. Not foolproof but fairly robust? What do you think @jonc125 ?

**Comment by jonc125** [comment]
I'm inclined to agree. Being able to do a diff on the generated code and skim by eye for obvious first errors would have been handy, but not if it's so much more work than just simulating the new code! The main challenge with the latter approach is it can be harder to track down the causes of differences, but what you've done so far should help a lot.

--
Written on a smartphone; please excuse brevity!

________________________________

**Comment by MichaelClerx** [comment]
But why would we have 1000s of lines of code? We could just generate code with pycml, store that, and then edit if it turns out its doing something silly somewhere?

**Comment by MichaelClerx** [comment]
(Checking sim output or even the output of a single RHS eval isn't super easy either. You get different floating point errors depending on how you order the equations, and if you apply simplifications etc., so again requires manual intervention to say when two things are "equal enough")

**Comment by MichaelClerx** [comment]
I would suggest this pipeline:

1. Generate test cases with pycml, storing the output
2. Recreate as close as sensible, check with testing framework
3. If fails, use diff to compare expected and returned code
4. If found to be a pycml artefact, then update the "expected" file to do what cellmlmanip does

So no need to read everything yourself, just chase the errors and update your static expected files

**Comment by mirams** [comment]
`wc -l *.cpp` for my generated c++ in the ApPredict project gives: 460269 !!

**Comment by MichaelClerx** [comment]
Well (A) that's too many tests cases, and (B) surely only a handful of those will give us errors?

**Comment by MauriceHendrix** [comment]
> Well (A) that's too many tests cases, and (B) surely only a handful of those will give us errors?

yes that's too many

Sadly all of them will give errors as generated code will be totally different:
- different order of equations
- different order of terms in equations
- and now different number of equations

**Comment by jonc125** [comment]
We certainly should - and will - test sim output, as when pycml is replaced the existing tests will then test our new code. The question is just the easiest & most reliable way to get there.

**Comment by MichaelClerx** [comment]
Can we do it in stages?

My stage 1 would be evaluate the RHS from the initial conditions in the CellML file, and see if the results match to some threshold we'll have to come up with

Stage 2 could be a simulation, which explores a bit more of the state space, but not the parameter space

After that it gets very user-dependent. Some models have states that stay 0 unless initialised as non-zero, but you'd have to know that to write the tests. Some models have parameters that radically change the model, so you'd have to know about that. You could muck stage 2 up deliberately with a chaotic model...

**Comment by MichaelClerx** [comment]
(Or you could build a kind of "web lab" tool, that tested several models using a series of model-independent protocols! Imagine that!)

**Comment by MichaelClerx** [comment]
Maybe stage 0 would be checking if the generated code compiles?

**Comment by MauriceHendrix** [comment]
> Maybe stage 0 would be checking if the generated code compiles?

Not automatically, not without chaste anyway.

**Comment by MauriceHendrix** [comment]
To be fair the chaste gen code becomes a lot simpler if I I don't try to replicate those linker variables

**Comment by MauriceHendrix** [comment]
And Just noticed it's also quite easy to recognize and resolve these linker variables in the reference output
