### ISSUE TITLE
Expand the range of supported MathML

### ISSUE THREAD

**Issue by jonc125** [ModellingWebLab/cellmlmanip#9]
We should probably support the [CellML subset](https://www.cellml.org/specifications/cellml_1.1/#sec_math_cellml_subset) eventually (see also in [CellML 2](https://docs.google.com/document/d/1MleZJF6DYp4FO4vxslAHInrRFMqrSpARa1s_dPhwYU0/edit#heading=h.zegia3mrify8)). Not urgent though - just the elements in the models we have currently is sufficient to get started :)

**Comment by nickerso** [comment]
I think the CellML 2.0 spec better represents the range of math actually used in practice. The 1.1 subset has a bunch of MathML elements that no CellML tool has ever supported so not sure there would be any benefit supporting them all.

**Comment by tamuri** [comment]
From the CellML 2.0 documentation, we still have to add:

```
* <cn type="e-notation">, <sep>
* <neq>, <xor>, <not>
* <ceiling>, <min>, <max>
* <logbase>, <degree> (child of <root> or <diff>)
* <sin>, <tan>, <sec>, <csc>, <cot>, <sinh>, <cosh>,<sech>, <csch>, <coth>, <arcsin>, 
  <arctan>, <arcsec>, <arccsc>, <arccot>, <arcsinh>,  <arccosh>, <arctanh>, <arcsech>, 
  <arccsch>, <arccoth>
* <exponentiale>, <notanumber>, <infinity>, <true>, <false>
```

**Comment by MichaelClerx** [comment]
CellML 1.0 is still most common though, so we shoud compare the specs and make sure we at least warn (or raise a `NotImplementedException`) when the other CellML 1 elements (e.g. `<factorial>`) are used

```<cn>, <ci>, <apply>, <piecewise>, <piece>, <otherwise>
<eq>, <neq>, <gt>, <lt>, <geq>, <leq>, <plus>, <minus>, <times>, <divide>, <power>, <root>, <abs>, <exp>, <ln>, <log>, <floor>, <ceiling>, <factorial>, <and>, <or>, <xor>, <not>, <diff>, <degree>, <bvar>, <logbase>, <sin>, <cos>, <tan>, <sec>, <csc>, <cot>, <sinh>, <cosh>, <tanh>, <sech>, <csch>, <coth>,
<arcsin>, <arccos>, <arctan>, <arccosh>, <arccot>, <arccoth>, <arccsc>, <arccsch>, <arcsec>, <arcsech>, <arcsinh>, <arctanh>, <true>, <false>, <notanumber>, <pi>, <infinity>, <exponentiale>
<semantics>, <annotation>, <annotation-xml>```

(the last 3 should also just trigger an exception/warning)
(I'd prefer exceptions, as warnings are more likely to go unnoticed, esp. when running IDEs where the console output is not shown to the user)

**Comment by nickerso** [comment]
The idea of the MathML subset in 2.0 is that it only includes the MathML that people have actually been using. Anything else is unlikely to ever be seen in a CellML model.

**Comment by MichaelClerx** [comment]
I'm with you 100%, but we have to be fair to new users who read the spec :)
So implement if easy, give an excellent error message if not. It wouldn't be fair to ignore the old specs because we've learned since then :)
