### ISSUE TITLE
Add warning if cellml has used numbers with different units

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#90]
I created a cellml file that states a (ms) = 1 (ms) + 1 (second). The transpiler merely adds these producing 2 (dimensionless) and so when calculating units further on code cannot catch the error.

Need to decide whether we try and catch it - and whether we throw an error or merely log a warning

**Comment by jonc125** [comment]
I think this is reflected in whether you get the graph with dummies still in, or after substitution. If before, you can spot these issues; if after you can't. So I think this isn't an issue and can be closed?

**Comment by MichaelClerx** [comment]
I actually just fixed this in #148! https://github.com/ModellingWebLab/cellmlmanip/pull/148#issuecomment-557276062

**Comment by MichaelClerx** [comment]
I just fixed this behaviour in #148

See `tests/test_model_bad_units.py`
