### ISSUE TITLE
get_initial_value bug and possible get_equations_for bug

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/cellmlmanip#92]
I think I have discovered a bug (let me know if I'm missing something!) 
This bug is preventing me from continuing with chaste code gen!
The model which I'm working with is attached

What I'm doing is:
`membrane_capacitance = self._model.get_symbol_by_ontology_term(self._OXMETA, "membrane_capacitance")`
`initial_value = self._model.get_initial_value(membrane_capacitance))`
and I get a `KeyError`

The model has a membrane_capacitance with an initial value.

Second issue, but I am less sure of this: should the capacitence not show up in the following? (it doesn't):
`membrane_stimulus_current = self._model.get_symbol_by_ontology_term(self._OXMETA, "membrane_stimulus_current")`
`self._model.get_equations_for([membrane_stimulus_current ])`

[aslanidi_model_2009.zip](https://github.com/ModellingWebLab/cellmlmanip/files/3676516/aslanidi_model_2009.zip)

**Comment by MauriceHendrix** [comment]
incidentally if I do
`self._model.get_equations_for([membrane_capacitance])`
I do get the equation:
`'[Eq(_membrane$Cm, 5.0e-5)]'`

**Comment by jonc125** [comment]
Seems like the field that `get_initial_value` reads is only set through calling `get_equation_graph`, so you'd (currently) need to call that method first. It might make more sense if `get_initial_value` used `self.dummy_metadata[symbol].initial_value`?

**Comment by jonc125** [comment]
Looking at the definition of `i_Stim` in that model, I can't see any mention of `Cm` so I think you're seeing the expected behaviour there.

**Comment by MauriceHendrix** [comment]
> Looking at the definition of `i_Stim` in that model, I can't see any mention of `Cm` so I think you're seeing the expected behaviour there.

ok that's fine.

**Comment by MauriceHendrix** [comment]
> Seems like the field that `get_initial_value` reads is only set through calling `get_equation_graph`, so you'd (currently) need to call that method first. It might make more sense if `get_initial_value` used `self.dummy_metadata[symbol].initial_value`?

in any case I wouldn't expect to get back a KeyError from that method, or if it does the docstring should warn me that this might happen I think.. As it happens the equation I get with get_equations_for is actually what I'm really after so it's no longer blocking me but still worth fixing.
