### ISSUE TITLE
Improve docstrings and create API documentation

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#93]
Todo:

- [x] Add rst docs, add a `[docs]` option in setup.py to install sphinx
- [x] Add some initial files, covering the main classes
- [x] Check all docstrings are capitalised, punctuated, and follow the format (1 sentence w short explanation + blank line + additional info), with parameters ~given in numpy style (seems to be the most common in the docstrings at the moment)~
- [x] Set up automatic doc building and hosting with readthedocs.io ?

**Comment by skeating** [comment]
@MichaelClerx can you paste a 'gold standard'  example so we are all on the same page

**Comment by MichaelClerx** [comment]
For PINTS we've just started using something like this:

```
def eat_biscuits(self, n, tea_factory=None):
    Attempts to eat ``n`` biscuits from the central biscuit repository.
    
    Biscuits will be eaten from best to worst, in the order defined by
    :meth:`cellmlmanip.order_biscuits`, using the algorithm defined in [1]_. An
    optional :class:`cellmlmanip.TeaFactory` can be passed in which may improve
    performance.
        
    Parameters
    ----------
    n : int
        The maximum number of biscuits to eat.
    tea_factory
        An optional :class:`cellmlmanip.TeaFactory` (or ``None``) to aid in
        digesting particularly dry biscuits.
    
    Returns
    -------
    n_eaten : int
        The actual number of biscuits eaten.
    rating : dict
        A dictionary mapping eaten :clas:`cellmlmanip.Biscuit` objects to a
        rating.
    
    References
    ----------
    .. [1] An improved biscuit eating algorithm.
           Clerx (2019) Computational Statistics.
           https://doi.org/10.1007/s001800050022
```

where all parts except the first line are optional:

- Parameter lists only make sense if there are several parameters, or if they have tricky meanings
- Parameter types are optional, but nice
- Return types are usually obvious enough as well, except if you return tuples
- References are nice if you're using some complicated algorithm

**Comment by MichaelClerx** [comment]
Another possible syntax for args and returns is the "google syntax":

```
Args:
    path (str): The path of the file to wrap
    field_storage (FileStorage): The :class:`FileStorage` instance to wrap
    temporary (bool): Whether or not to delete the file when the File
       instance is destructed

Returns:
    BufferedFileStorage: A buffered writable file descriptor
```

Both can be rendered by sphinx, if we use the (very well supported) [napolean](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html) extension

**Comment by MichaelClerx** [comment]
Bit much for some projects, but I think `cellmlmanip` in particular is meant to last?

**Comment by skeating** [comment]
This is very different from the 'standard' python docstrings that are already there. I'll try and use this with new functions - but it may be a while before all functions have this type of documentation.

**Comment by MichaelClerx** [comment]
We can maybe discuss it with e.g. @jonc125 first. Not sure how high of a priority this is

**Comment by jonc125** [comment]
I wouldn't bother with a massive trawl through existing docs, but worth remembering for new stuff or when edits are made.

Don't we use the
```
:param name: description
```
type syntax in various parts of the code at present? Which is also supported by Sphinx! Pity Python hasn't standardised this yet...

**Comment by MichaelClerx** [comment]
> :param name: description

Yeah happy to write some model docstring based on that too!

**Comment by MichaelClerx** [comment]
Just improving docstrings left on this issue, which we can do as we go along
