### ISSUE TITLE
State variables in wrong order

### ISSUE THREAD

**Issue by MauriceHendrix** [ModellingWebLab/cellmlmanip#95]
I'm getting the state variables in the order and hence my regression test fails.

The order matters somewhat as all existing chaste tests working relies on this order not changing.

I am expecting:

`[_membrane$V,
_sodium_current_m_gate$m,
_sodium_current_h1_gate$h1,
_sodium_current_h2_gate$h2,
_L_type_Ca_channel_d_L_gate$d_L,
_L_type_Ca_channel_f_L_gate$f_L,
_T_type_Ca_channel_d_T_gate$d_T,
_T_type_Ca_channel_f_T_gate$f_T,
_Ca_independent_transient_outward_K_current_r_gate$r,
_Ca_independent_transient_outward_K_current_s1_gate$s1,
_Ca_independent_transient_outward_K_current_s2_gate$s2,
_Ca_independent_transient_outward_K_current_s3_gate$s3,
_delayed_rectifier_K_current_z_gate$z,
_delayed_rectifier_K_current_pa_gate$p_a,
_delayed_rectifier_K_current_pi_gate$p_i,
_intracellular_ion_concentrations$Na_i,

**_intracellular_ion_concentrations$Ca_i,
_intracellular_ion_concentrations$K_i,**

_intracellular_Ca_buffering$O_C,
_intracellular_Ca_buffering$O_TC,
_intracellular_Ca_buffering$O_TMgC,
_intracellular_Ca_buffering$O_TMgMg,
_cleft_space_ion_concentrations$K_c,

**_Ca_handling_by_the_SR$Ca_rel,
_Ca_handling_by_the_SR$Ca_up,
_Ca_handling_by_the_SR$O_Calse,**

_Ca_handling_by_the_SR$F1,
_Ca_handling_by_the_SR$F2,
_Ca_handling_by_the_SR$F3]

But am getting:

[_membrane$V,
_sodium_current_m_gate$m,
_sodium_current_h1_gate$h1,
_sodium_current_h2_gate$h2,
_L_type_Ca_channel_d_L_gate$d_L,
_L_type_Ca_channel_f_L_gate$f_L,
_T_type_Ca_channel_d_T_gate$d_T,
_T_type_Ca_channel_f_T_gate$f_T,
_Ca_independent_transient_outward_K_current_r_gate$r,
_Ca_independent_transient_outward_K_current_s1_gate$s1,
_Ca_independent_transient_outward_K_current_s2_gate$s2,
_Ca_independent_transient_outward_K_current_s3_gate$s3,
_delayed_rectifier_K_current_z_gate$z,
_delayed_rectifier_K_current_pa_gate$p_a,
_delayed_rectifier_K_current_pi_gate$p_i,
_intracellular_ion_concentrations$Na_i,

**_intracellular_ion_concentrations$K_i,
_intracellular_ion_concentrations$Ca_i,**

_intracellular_Ca_buffering$O_C,
_intracellular_Ca_buffering$O_TC,
_intracellular_Ca_buffering$O_TMgC,
_intracellular_Ca_buffering$O_TMgMg,
_cleft_space_ion_concentrations$K_c,

**_Ca_handling_by_the_SR$O_Calse,
_Ca_handling_by_the_SR$Ca_rel,
_Ca_handling_by_the_SR$Ca_up,**

_Ca_handling_by_the_SR$F1,
_Ca_handling_by_the_SR$F2,
_Ca_handling_by_the_SR$F3]

[aslanidi_model_2009.zip](https://github.com/ModellingWebLab/cellmlmanip/files/3678397/aslanidi_model_2009.zip)

**Comment by MauriceHendrix** [comment]
right so I think I know how pycml does it. if I look at the cellml at the component there first is a block with variable name declarations and then the maths. The declarations block seems to determine the order.

**Comment by jonc125** [comment]
From what I recall pycml uses document order by default, which should indeed be the order in which variables get parsed from the model.
