### ISSUE TITLE
Shortcut for get_conversion_factor

### ISSUE THREAD

**Issue by skeating** [ModellingWebLab/cellmlmanip#97]
Maurice requested a short-cut for
"factor = model.units.get_conversion_factor(1 * current_units, secondary_units)
ideally I guess I'd do something like factor = model.get_conversion_factor(eq.lhs, desired_units) (and return 1.0 if the units are the same)?"

I would also provide a function
get_conversion_factor(unit, to_unit)

If I do this by overloading the existing function I will have to give the arguments keywords - and thus break any existing code. 

Options are:
1. add keyword arguments and break code (but then you would be able to have convert express -> unit; quantity -> unit; unit -> unit)
2. Leave existing function as is and create a new function with the keyword args. So we get all functionality, dont break code BUT would need a newly named function e.g. get_convers_factor or some variant

Thoughts ??

**Comment by jonc125** [comment]
We're very much at alpha stage with these libraries. Renaming and breaking existing code is fine if it makes for a more consistent API! We're the only users after all :)

**Comment by skeating** [comment]
Okay I've use the existing function name with keyword args; so code may break. See https://github.com/ModellingWebLab/cellmlmanip/pull/98
