### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/cellmlmanip#99]
Cellmlmanip (and weblab_cg) are intended to last for quite a while, and be useful for weblab & chaste for a long time, so I think it'd be worth it to have a (short!) document spelling out any coding standards we're using, and to provide the info that new people will need to get up to speed with developing / debugging cellmlmanip

**Comment by jonc125** [comment]
See #137.
